// Модели бизнес-процессов в нотации BPMN. Каждая схема описывает реальный процесс
// платформы: триггер, шаги участников и системы, точки принятия решений и SLA из ТЗ.
//
// col — колонка в сетке, row — строка внутри дорожки. Раскладка считается рендерером.
//
// Альбом разделён на два пользовательских пути: подача полноценной инициативы
// (конвейер Stage-Gate) и обсуждение идей (быстрый вход с решениями коллег).
// Поле scenario у каждой схемы указывает, какому пути она принадлежит.

const L = {
  emp: { id: 'emp', title: 'Сотрудник учреждения' },
  head: { id: 'head', title: 'Руководитель учреждения' },
  expert: { id: 'expert', title: 'Эксперт ДТСЗН' },
  dev: { id: 'dev', title: 'Команда разработки и ЦТ' },
  supplier: { id: 'supplier', title: 'Поставщик' },
  pilot: { id: 'pilot', title: 'Координатор пилотов' },
  dtszn: { id: 'dtszn', title: 'ДТСЗН (центральный аппарат)' },
  sys: { id: 'sys', title: 'Платформа Social1' },
  // Роли модуля «Идеи и решения». Это не отдельные учётные записи, а функции,
  // которые исполняют существующие роли платформы.
  adv: { id: 'adv', title: 'Советчик — сотрудник любого учреждения' },
  rev: { id: 'rev', title: 'Ревьюер — любой сотрудник' },
  mod: { id: 'mod', title: 'Модератор модуля — эксперт ДТСЗН' },
};

export const DIAGRAMS = [
  // ══════════════════════════════════════════════════════════
  {
    id: 'e2e', role: 'all', scenario: 'initiative', group: 'Сквозной процесс',
    title: 'Полный цикл: от проблемы до масштабирования',
    description: 'Инициатива проходит шесть стадий и пять точек принятия решений. Работы отделены от решений: на каждой точке ответственный участник выбирает Go, Kill, Hold или Redirect на основе доказательств.',
    lanes: [L.emp, L.head, L.expert, L.dev, L.pilot, L.dtszn],
    nodes: [
      { id: 'st', type: 'start', lane: 'emp', col: 0, row: 0, label: 'Обнаружена проблема в ежедневной работе' },
      { id: 'form', type: 'user', lane: 'emp', col: 1, row: 0, label: 'Сформулировать и подать инициативу' },
      { id: 'g1in', type: 'message', lane: 'head', col: 2, row: 0, label: 'Инициатива поступила руководителю' },
      { id: 'g1eval', type: 'user', lane: 'head', col: 3, row: 0, label: 'Оценить по критериям Gate 1' },
      { id: 'g1', type: 'xor', lane: 'head', col: 4, row: 0, label: 'Gate 1 — 3 рабочих дня' },
      { id: 'g1kill', type: 'end', lane: 'head', col: 4, row: 1, label: 'Kill: отказ с обоснованием' },
      { id: 'g2eval', type: 'user', lane: 'expert', col: 5, row: 0, label: 'Экспертиза: стратегия, масштабируемость, риски' },
      { id: 'g2', type: 'xor', lane: 'expert', col: 6, row: 0, label: 'Gate 2 — 5 рабочих дней' },
      { id: 'g2back', type: 'end', lane: 'expert', col: 6, row: 1, label: 'Kill / Redirect: возврат автору' },
      { id: 'build', type: 'user', lane: 'dev', col: 7, row: 0, label: 'Разработать MVP: 4 спринта по 2 недели' },
      { id: 'g3', type: 'xor', lane: 'dev', col: 8, row: 0, label: 'Gate 3 — готовность прототипа' },
      { id: 'run', type: 'user', lane: 'pilot', col: 9, row: 0, label: 'Провести пилот в учреждении — 1 месяц' },
      { id: 'fb', type: 'service', lane: 'pilot', col: 10, row: 0, label: 'Собрать обратную связь и KPI — 1 неделя' },
      { id: 'g4', type: 'xor', lane: 'pilot', col: 11, row: 0, label: 'Gate 4 — результаты пилота' },
      { id: 'g4back', type: 'end', lane: 'pilot', col: 11, row: 1, label: 'Kill / Redirect: доработка прототипа' },
      { id: 'g5', type: 'xor', lane: 'dtszn', col: 12, row: 0, label: 'Gate 5 — решение о масштабировании' },
      { id: 'scale', type: 'user', lane: 'dtszn', col: 13, row: 0, label: 'Тиражировать: обучение и методические материалы' },
      { id: 'fin', type: 'end', lane: 'dtszn', col: 14, row: 0, label: 'Улучшение внедрено в учреждениях' },
      { id: 'g5keep', type: 'end', lane: 'dtszn', col: 12, row: 1, label: 'Сохранить как практику без тиражирования' },
    ],
    flows: [
      { from: 'st', to: 'form' }, { from: 'form', to: 'g1in', kind: 'message' },
      { from: 'g1in', to: 'g1eval' }, { from: 'g1eval', to: 'g1' },
      { from: 'g1', to: 'g2eval', label: 'Go' }, { from: 'g1', to: 'g1kill', label: 'Kill / Hold' },
      { from: 'g2eval', to: 'g2' },
      { from: 'g2', to: 'build', label: 'Go' }, { from: 'g2', to: 'g2back', label: 'Kill / Redirect' },
      { from: 'build', to: 'g3' },
      { from: 'g3', to: 'run', label: 'Go' },
      { from: 'run', to: 'fb' }, { from: 'fb', to: 'g4' },
      { from: 'g4', to: 'g5', label: 'Go' }, { from: 'g4', to: 'g4back', label: 'Kill / Redirect' },
      { from: 'g5', to: 'scale', label: 'Go' }, { from: 'g5', to: 'g5keep', label: 'Kill' },
      { from: 'scale', to: 'fin' },
    ],
    walkthrough: [
      { node: 'st', title: 'Триггер процесса', body: 'Всё начинается не с распоряжения сверху, а с проблемы, которую сотрудник видит в своей работе: избыточная операция, потеря времени, неудобство для гражданина.' },
      { node: 'form', title: 'Формулировка инициативы', body: 'Сотрудник описывает проблему, предлагаемое решение и ожидаемый эффект. Этап 1 не содержит точки принятия решения — инициатива уходит дальше автоматически.' },
      { node: 'g1', title: 'Gate 1 — первый фильтр', body: 'Руководитель учреждения оценивает соответствие регламентам и потенциал локального улучшения. Срок — 3 рабочих дня; платформа отслеживает его и эскалирует просрочку.' },
      { node: 'g2', title: 'Gate 2 — стратегическая оценка', body: 'Эксперты ДТСЗН смотрят шире: совместимость с целями Департамента, потенциал масштабирования, ожидаемый эффект, техническую осуществимость. Срок — 5 рабочих дней.' },
      { node: 'build', title: 'Разработка прототипа', body: 'Команда цифровой трансформации создаёт минимально жизнеспособный продукт по Agile. Приоритеты каждого спринта утверждает продакт-менеджер ДТСЗН.' },
      { node: 'run', title: 'Проверка в реальной работе', body: 'Пилотное учреждение внедряет прототип на месяц. Собираются данные об эффективности, удобстве и влиянии на процессы — от сотрудников и от граждан.' },
      { node: 'g4', title: 'Gate 4 — доказательство эффекта', body: 'Ключевая точка: заявленный эффект должен подтвердиться фактическими данными пилота. Здесь отсеиваются решения, которые выглядели хорошо на бумаге.' },
      { node: 'g5', title: 'Gate 5 — решение о тиражировании', body: 'ДТСЗН оценивает подтверждённый эффект, готовность других учреждений и наличие ресурсов. Масштабирование должно начаться в течение 2 недель после решения.' },
      { node: 'fin', title: 'Конечный продукт экосистемы', body: 'Не база предложений, а поток реально внедрённых улучшений. Именно этот показатель платформа считает главным.' },
    ],
  },

  // ══════════════════════════════ СОТРУДНИК ══════════════════
  {
    id: 'emp-submit', role: 'employee', scenario: 'initiative', group: 'Сотрудник учреждения',
    title: 'Подача инициативы',
    description: 'Путь от обнаруженной проблемы до задачи в кабинете руководителя. Платформа помогает не дублировать чужие усилия и сама маршрутизирует инициативу.',
    lanes: [L.emp, L.sys],
    nodes: [
      { id: 'st', type: 'start', lane: 'emp', col: 0, row: 0, label: 'Обнаружена проблема в процессе или услуге' },
      { id: 'search', type: 'user', lane: 'emp', col: 1, row: 0, label: 'Проверить похожие идеи на доске' },
      { id: 'gdup', type: 'xor', lane: 'emp', col: 2, row: 0, label: 'Похожая идея уже есть?' },
      { id: 'support', type: 'user', lane: 'emp', col: 3, row: 1, label: 'Поддержать голосом и дополнить комментарием' },
      { id: 'endsup', type: 'end', lane: 'emp', col: 4, row: 1, label: 'Усилия объединены, дублирование исключено' },
      { id: 'fill', type: 'user', lane: 'emp', col: 3, row: 0, label: 'Заполнить форму: проблема, решение, эффект' },
      { id: 'ai', type: 'service', lane: 'sys', col: 4, row: 0, label: 'Определить направление и найти похожие инициативы' },
      { id: 'check', type: 'user', lane: 'emp', col: 5, row: 0, label: 'Уточнить описание и измерить эффект числом' },
      { id: 'send', type: 'user', lane: 'emp', col: 6, row: 0, label: 'Отправить инициативу' },
      { id: 'num', type: 'service', lane: 'sys', col: 7, row: 0, label: 'Присвоить номер, создать задачу руководителю' },
      { id: 'wait', type: 'timer', lane: 'emp', col: 8, row: 0, label: 'Ожидание решения Gate 1 — 3 рабочих дня' },
      { id: 'end', type: 'end', lane: 'emp', col: 9, row: 0, label: 'Получено решение с обоснованием' },
    ],
    flows: [
      { from: 'st', to: 'search' }, { from: 'search', to: 'gdup' },
      { from: 'gdup', to: 'support', label: 'да' }, { from: 'support', to: 'endsup' },
      { from: 'gdup', to: 'fill', label: 'нет' },
      { from: 'fill', to: 'ai', kind: 'message' }, { from: 'ai', to: 'check', kind: 'message' },
      { from: 'check', to: 'send' }, { from: 'send', to: 'num', kind: 'message' },
      { from: 'num', to: 'wait', kind: 'message' }, { from: 'wait', to: 'end' },
    ],
    walkthrough: [
      { node: 'search', title: 'Сначала посмотрите раздел «Идеи и решения»', body: 'Часто проблему уже сформулировал коллега из другого учреждения — а иногда там же лежит и готовое решение, которое у кого-то работает. Присоединиться к существующей идее быстрее, чем вести свою с нуля.' },
      { node: 'gdup', title: 'Развилка: поддержать или подать своё', body: 'Если совпадение высокое — поддержите голосом и добавьте свой контекст в комментарии. Решение сразу будет проектироваться под несколько типов учреждений.' },
      { node: 'fill', title: 'Четыре вопроса обычным языком', body: 'Какую проблему обнаружили, что предлагаете, какой эффект это даст и чем он измеряется. Технических навыков форма не требует.' },
      { node: 'ai', title: 'ИИ-подсказчик работает по ходу', body: 'Пока вы пишете, система определяет тематическое направление и показывает похожие инициативы с процентом совпадения. Классификация носит рекомендательный характер.' },
      { node: 'check', title: 'Цифра усиливает инициативу', body: 'Даже приблизительная оценка эффекта позволит на пилоте сравнить прогноз с фактом. Это поле эксперты читают внимательнее всего.' },
      { node: 'num', title: 'Дальше платформа действует сама', body: 'Инициатива получает номер вида SOC-2026-0001 и уходит руководителю вашего учреждения: этап 1 не содержит точки принятия решения.' },
      { node: 'wait', title: 'Срок отслеживается системой', body: 'Три рабочих дня считаются с пропуском выходных. Если решение не принято вовремя, задача эскалируется координатору экосистемы.' },
    ],
  },
  {
    id: 'emp-pilot', role: 'employee', scenario: 'initiative', group: 'Сотрудник учреждения',
    title: 'Участие в пилоте и обратная связь',
    description: 'Сотрудники пилотного учреждения применяют прототип в реальной работе. Их отклики — основное доказательство на Gate 4.',
    lanes: [L.emp, L.sys, L.pilot],
    nodes: [
      { id: 'st', type: 'message', lane: 'emp', col: 0, row: 0, label: 'Учреждение выбрано пилотной площадкой' },
      { id: 'learn', type: 'user', lane: 'emp', col: 1, row: 0, label: 'Пройти обучение работе с прототипом' },
      { id: 'use', type: 'user', lane: 'emp', col: 2, row: 0, label: 'Применять решение в ежедневной работе' },
      { id: 'issue', type: 'xor', lane: 'emp', col: 3, row: 0, label: 'Возникла проблема?' },
      { id: 'report', type: 'user', lane: 'emp', col: 4, row: 1, label: 'Сообщить в обсуждении инициативы' },
      { id: 'timer', type: 'timer', lane: 'emp', col: 4, row: 0, label: 'Пилотный период — 1 месяц' },
      { id: 'survey', type: 'user', lane: 'emp', col: 5, row: 0, label: 'Заполнить опрос по итогам пилота' },
      { id: 'nlp', type: 'service', lane: 'sys', col: 6, row: 0, label: 'Разобрать отклики: тональность, темы, сигналы' },
      { id: 'analyse', type: 'user', lane: 'pilot', col: 7, row: 0, label: 'Сопоставить отклики с фактическими KPI' },
      { id: 'end', type: 'end', lane: 'pilot', col: 8, row: 0, label: 'Доказательная база для Gate 4 готова' },
    ],
    flows: [
      { from: 'st', to: 'learn' }, { from: 'learn', to: 'use' }, { from: 'use', to: 'issue' },
      { from: 'issue', to: 'report', label: 'да' }, { from: 'report', to: 'use' },
      { from: 'issue', to: 'timer', label: 'нет' },
      { from: 'timer', to: 'survey' }, { from: 'survey', to: 'nlp', kind: 'message' },
      { from: 'nlp', to: 'analyse', kind: 'message' }, { from: 'analyse', to: 'end' },
    ],
    walkthrough: [
      { node: 'learn', title: 'Обучение — до старта пилота', body: 'Опыт завершённых пилотов показал: если учить в первый день, вся первая неделя уходит на освоение и портит статистику.' },
      { node: 'issue', title: 'Проблемы фиксируются сразу', body: 'Не копите замечания до финального опроса. Сообщение в обсуждении инициативы попадает напрямую команде разработки.' },
      { node: 'survey', title: 'Опрос — не формальность', body: 'Шкала удобства, влияние на рабочее время и свободный отзыв. Именно эти данные защищают инициативу на Gate 4.' },
      { node: 'nlp', title: 'Тексты разбираются автоматически', body: 'Свободные ответы проходят разбор: тональность, повторяющиеся темы, отдельно выделенные проблемные сигналы с цитатами.' },
      { node: 'end', title: 'Что решает судьбу инициативы', body: 'Доказанность эффекта, удовлетворённость пользователей, отсутствие критических проблем и соблюдение требований к защите данных.' },
    ],
  },

  // ══════════════════════════════ РУКОВОДИТЕЛЬ ═══════════════
  {
    id: 'head-gate1', role: 'head', scenario: 'initiative', group: 'Руководитель учреждения',
    title: 'Решение на Gate 1',
    description: 'Первый уровень контроля. Руководитель — владелец процессов и заказчик изменений в своём учреждении.',
    sla: '3 рабочих дня',
    lanes: [L.sys, L.head, L.emp],
    nodes: [
      { id: 'task', type: 'message', lane: 'sys', col: 0, row: 0, label: 'Задача на Gate 1 в кабинете руководителя' },
      { id: 'read', type: 'user', lane: 'head', col: 1, row: 0, label: 'Изучить проблему и предлагаемое решение' },
      { id: 'votes', type: 'user', lane: 'head', col: 2, row: 0, label: 'Посмотреть поддержку коллег и похожие инициативы' },
      { id: 'crit', type: 'user', lane: 'head', col: 3, row: 0, label: 'Оценить по трём критериям Gate 1' },
      { id: 'gw', type: 'xor', lane: 'head', col: 4, row: 0, label: 'Решение с обязательной аргументацией' },
      { id: 'go', type: 'service', lane: 'sys', col: 5, row: 0, label: 'Передать на экспертизу ДТСЗН' },
      { id: 'hold', type: 'user', lane: 'head', col: 5, row: 1, label: 'Запросить недостающие сведения у автора' },
      { id: 'redir', type: 'user', lane: 'head', col: 5, row: 2, label: 'Вернуть автору на доработку' },
      { id: 'kill', type: 'end', lane: 'head', col: 5, row: 3, label: 'Остановлено: обоснование в архиве знаний' },
      { id: 'endgo', type: 'end', lane: 'sys', col: 6, row: 0, label: 'Инициатива на этапе экспертизы' },
      { id: 'notify', type: 'message', lane: 'emp', col: 6, row: 1, label: 'Автор уведомлён и дополняет инициативу' },
      { id: 'sla', type: 'timer', lane: 'head', col: 3, row: 1, label: 'Истекли 3 рабочих дня' },
      { id: 'esc', type: 'end', lane: 'head', col: 4, row: 1, label: 'Эскалация координатору экосистемы' },
    ],
    flows: [
      { from: 'task', to: 'read', kind: 'message' }, { from: 'read', to: 'votes' },
      { from: 'votes', to: 'crit' }, { from: 'crit', to: 'gw' },
      { from: 'gw', to: 'go', label: 'Go' }, { from: 'go', to: 'endgo' },
      { from: 'gw', to: 'hold', label: 'Hold' }, { from: 'hold', to: 'notify', kind: 'message' },
      { from: 'gw', to: 'redir', label: 'Redirect' }, { from: 'redir', to: 'notify', kind: 'message' },
      { from: 'gw', to: 'kill', label: 'Kill' },
      { from: 'read', to: 'sla', label: 'решение не принято' }, { from: 'sla', to: 'esc' },
    ],
    walkthrough: [
      { node: 'task', title: 'Задачу создаёт движок процесса', body: 'Инициатива адресуется строго руководителю учреждения автора. Решить за чужое учреждение платформа не позволит.' },
      { node: 'votes', title: 'Поддержка коллег как контекст', body: 'Число голосов показывает, насколько проблема распространена. Это сигнал приоритета, но не замена вашей оценке.' },
      { node: 'crit', title: 'Критерии заданы заранее', body: 'Соответствие внутренним политикам, потенциал локального улучшения, реалистичность в рамках бюджета. Перечень настраивается администратором.' },
      { node: 'gw', title: 'Четыре решения, и все документируются', body: 'Go — продолжить. Kill — остановить: это не провал, а экономия ресурсов. Hold — приостановить до получения данных. Redirect — вернуть на доработку. Без аргументации система решение не примет.' },
      { node: 'kill', title: 'Отказ тоже приносит пользу', body: 'Обоснование попадает в архив знаний и уходит автору. Неудачная, но продуманная инициатива — часть учебного процесса, а не повод для санкций.' },
      { node: 'sla', title: 'Срок под контролем системы', body: 'Три рабочих дня считаются с пропуском выходных. Просроченная задача переходит в статус эскалации, координатор экосистемы получает уведомление.' },
    ],
  },
  {
    id: 'head-pilot', role: 'head', scenario: 'initiative', group: 'Руководитель учреждения',
    title: 'Заявка учреждения на роль пилотной площадки',
    description: 'Учреждение само предлагает себя площадкой для проверки прототипа в реальных условиях.',
    lanes: [L.head, L.pilot, L.emp],
    nodes: [
      { id: 'st', type: 'start', lane: 'head', col: 0, row: 0, label: 'На доске идей замечен подходящий прототип' },
      { id: 'assess', type: 'user', lane: 'head', col: 1, row: 0, label: 'Оценить готовность учреждения и ресурсы' },
      { id: 'apply', type: 'user', lane: 'head', col: 2, row: 0, label: 'Подать заявку с обоснованием' },
      { id: 'review', type: 'user', lane: 'pilot', col: 3, row: 0, label: 'Рассмотреть заявку площадки' },
      { id: 'gw', type: 'xor', lane: 'pilot', col: 4, row: 0, label: 'Площадка подходит?' },
      { id: 'no', type: 'end', lane: 'pilot', col: 5, row: 1, label: 'Отказ с пояснением' },
      { id: 'plan', type: 'user', lane: 'pilot', col: 5, row: 0, label: 'Запланировать пилот: сроки, KPI, участники' },
      { id: 'prep', type: 'user', lane: 'head', col: 6, row: 0, label: 'Выделить сотрудников и обеспечить условия' },
      { id: 'base', type: 'user', lane: 'head', col: 7, row: 0, label: 'Снять базовые значения показателей до старта' },
      { id: 'start', type: 'message', lane: 'emp', col: 8, row: 0, label: 'Сотрудники приступают к пилоту' },
    ],
    flows: [
      { from: 'st', to: 'assess' }, { from: 'assess', to: 'apply' },
      { from: 'apply', to: 'review', kind: 'message' }, { from: 'review', to: 'gw' },
      { from: 'gw', to: 'plan', label: 'да' }, { from: 'gw', to: 'no', label: 'нет' },
      { from: 'plan', to: 'prep', kind: 'message' }, { from: 'prep', to: 'base' },
      { from: 'base', to: 'start', kind: 'message' },
    ],
    walkthrough: [
      { node: 'assess', title: 'Готовность важнее энтузиазма', body: 'Нужны сотрудники, готовые работать по-новому месяц, и ответственный за сбор обратной связи. Без этого анкеты остаются незаполненными.' },
      { node: 'plan', title: 'KPI определяются до старта', body: 'Показатели берутся из заявленного эффекта инициативы: что именно должно измениться и на сколько.' },
      { node: 'base', title: 'Базовые замеры — обязательный шаг', body: 'Без значения «до» доказать эффект на Gate 4 невозможно. Снимайте показатели за одну-две недели до начала пилота.' },
    ],
  },
  {
    id: 'head-adopt', role: 'head', scenario: 'initiative', group: 'Руководитель учреждения',
    title: 'Внедрение практики из библиотеки',
    description: 'Масштабирование «снизу»: учреждение берёт проверенное решение по собственной инициативе, без директивы сверху.',
    lanes: [L.head, L.sys, L.dtszn],
    nodes: [
      { id: 'st', type: 'start', lane: 'head', col: 0, row: 0, label: 'Поиск решения похожей проблемы' },
      { id: 'lib', type: 'user', lane: 'head', col: 1, row: 0, label: 'Изучить библиотеку лучших практик' },
      { id: 'eff', type: 'user', lane: 'head', col: 2, row: 0, label: 'Проверить подтверждённый эффект и материалы' },
      { id: 'gw', type: 'xor', lane: 'head', col: 3, row: 0, label: 'Практика применима у нас?' },
      { id: 'no', type: 'end', lane: 'head', col: 4, row: 1, label: 'Продолжить поиск или подать свою инициативу' },
      { id: 'take', type: 'user', lane: 'head', col: 4, row: 0, label: 'Взять практику в работу' },
      { id: 'mark', type: 'service', lane: 'sys', col: 5, row: 0, label: 'Отметить внедрение как инициативное' },
      { id: 'train', type: 'user', lane: 'head', col: 6, row: 0, label: 'Обучить сотрудников по готовым материалам' },
      { id: 'done', type: 'user', lane: 'head', col: 7, row: 0, label: 'Подтвердить внедрение' },
      { id: 'metric', type: 'service', lane: 'dtszn', col: 8, row: 0, label: 'Учесть в показателе масштабирования «снизу»' },
      { id: 'end', type: 'end', lane: 'dtszn', col: 9, row: 0, label: 'Практика распространяется без директив' },
    ],
    flows: [
      { from: 'st', to: 'lib' }, { from: 'lib', to: 'eff' }, { from: 'eff', to: 'gw' },
      { from: 'gw', to: 'take', label: 'да' }, { from: 'gw', to: 'no', label: 'нет' },
      { from: 'take', to: 'mark', kind: 'message' }, { from: 'mark', to: 'train', kind: 'message' },
      { from: 'train', to: 'done' }, { from: 'done', to: 'metric', kind: 'message' }, { from: 'metric', to: 'end' },
    ],
    walkthrough: [
      { node: 'lib', title: 'Внутренний рынок решений', body: 'В библиотеке только практики, доказавшие эффект на пилоте: с методическими материалами, программой обучения и типовыми документами.' },
      { node: 'mark', title: 'Почему это важно измерять', body: 'Внедрение по инициативе учреждения помечается отдельно. Доля таких внедрений — показатель зрелости экосистемы и силы внутренней сети знаний.' },
      { node: 'end', title: 'Изменения поднимаются снизу', body: 'Цель платформы — чтобы улучшения не только спускались сверху, но и системно распространялись между учреждениями по их собственной инициативе.' },
    ],
  },

  // ══════════════════════════════ ЭКСПЕРТ ════════════════════
  {
    id: 'expert-gate2', role: 'expert', scenario: 'initiative', group: 'Эксперт ДТСЗН',
    title: 'Экспертиза на Gate 2',
    description: 'Стратегическая оценка: соответствие целям Департамента, потенциал масштабирования, осуществимость.',
    sla: '5 рабочих дней',
    lanes: [L.sys, L.expert, L.dev],
    nodes: [
      { id: 'in', type: 'message', lane: 'sys', col: 0, row: 0, label: 'Инициатива прошла Gate 1' },
      { id: 'ctx', type: 'user', lane: 'expert', col: 1, row: 0, label: 'Изучить инициативу и решение руководителя' },
      { id: 'sim', type: 'service', lane: 'sys', col: 2, row: 0, label: 'Показать похожие инициативы и прогноз успеха' },
      { id: 'dup', type: 'xor', lane: 'expert', col: 3, row: 0, label: 'Дублирует существующую работу?' },
      { id: 'merge', type: 'user', lane: 'expert', col: 4, row: 1, label: 'Объединить с существующей инициативой' },
      { id: 'endm', type: 'end', lane: 'expert', col: 5, row: 1, label: 'Redirect: усилия объединены' },
      { id: 'crit', type: 'user', lane: 'expert', col: 4, row: 0, label: 'Оценить по четырём критериям Gate 2' },
      { id: 'feas', type: 'user', lane: 'dev', col: 5, row: 0, label: 'Подтвердить техническую осуществимость' },
      { id: 'gw', type: 'xor', lane: 'expert', col: 6, row: 0, label: 'Вердикт комитета экспертов' },
      { id: 'go', type: 'user', lane: 'expert', col: 7, row: 0, label: 'Сформировать KPI и передать в разработку' },
      { id: 'endgo', type: 'end', lane: 'dev', col: 8, row: 0, label: 'Проект разработки создан' },
      { id: 'kill', type: 'end', lane: 'expert', col: 7, row: 1, label: 'Kill: нежизнеспособные проекты отсеяны' },
      { id: 'hold', type: 'end', lane: 'expert', col: 7, row: 2, label: 'Hold: ожидание данных или ресурсов' },
    ],
    flows: [
      { from: 'in', to: 'ctx', kind: 'message' }, { from: 'ctx', to: 'sim', kind: 'message' },
      { from: 'sim', to: 'dup', kind: 'message' },
      { from: 'dup', to: 'merge', label: 'да' }, { from: 'merge', to: 'endm' },
      { from: 'dup', to: 'crit', label: 'нет' },
      { from: 'crit', to: 'feas', kind: 'message' }, { from: 'feas', to: 'gw', kind: 'message' },
      { from: 'gw', to: 'go', label: 'Go' }, { from: 'go', to: 'endgo', kind: 'message' },
      { from: 'gw', to: 'kill', label: 'Kill' }, { from: 'gw', to: 'hold', label: 'Hold' },
    ],
    walkthrough: [
      { node: 'sim', title: 'ИИ подсказывает, но не решает', body: 'Система показывает похожие инициативы с процентом совпадения и прогноз успеха с раскрытием факторов. Вердикт остаётся за экспертом.' },
      { node: 'dup', title: 'Дублирование — частая причина Redirect', body: 'Если проблема одна, а контекст разный, инициативы объединяются: решение сразу проектируется под несколько типов учреждений.' },
      { node: 'crit', title: 'Четыре критерия Gate 2', body: 'Стратегическая совместимость с целями Департамента, потенциал масштабирования, ожидаемый эффект, техническая осуществимость на уровне идеи.' },
      { node: 'go', title: 'KPI задаются здесь', body: 'Показатели, определённые на экспертизе, станут критериями оценки пилота на Gate 4. Их нельзя откладывать «на потом».' },
      { node: 'kill', title: 'Kill — признак здоровой системы', body: 'Решения об остановке не считаются негативным показателем: они экономят ресурсы и не дают нежизнеспособным проектам дойти до разработки.' },
    ],
  },
  {
    id: 'expert-practice', role: 'expert', scenario: 'initiative', group: 'Эксперт ДТСЗН',
    title: 'Публикация лучшей практики',
    description: 'Превращение доказавшего эффект решения в тиражируемую практику с материалами для внедрения.',
    lanes: [L.expert, L.pilot, L.head],
    nodes: [
      { id: 'st', type: 'message', lane: 'expert', col: 0, row: 0, label: 'Инициатива прошла Gate 4 или Gate 5' },
      { id: 'data', type: 'user', lane: 'pilot', col: 1, row: 0, label: 'Передать данные пилота и отклики участников' },
      { id: 'sum', type: 'user', lane: 'expert', col: 2, row: 0, label: 'Сформулировать суть решения без жаргона' },
      { id: 'eff', type: 'user', lane: 'expert', col: 3, row: 0, label: 'Описать подтверждённый эффект с цифрами' },
      { id: 'mat', type: 'user', lane: 'expert', col: 4, row: 0, label: 'Подготовить материалы: инструкции, обучение, типовые документы' },
      { id: 'pub', type: 'user', lane: 'expert', col: 5, row: 0, label: 'Опубликовать в библиотеке практик' },
      { id: 'award', type: 'service', lane: 'expert', col: 6, row: 0, label: 'Отметить автора инициативы признанием' },
      { id: 'take', type: 'user', lane: 'head', col: 7, row: 0, label: 'Учреждения берут практику в работу' },
      { id: 'end', type: 'end', lane: 'head', col: 8, row: 0, label: 'Решение распространяется по сети учреждений' },
    ],
    flows: [
      { from: 'st', to: 'data', kind: 'message' }, { from: 'data', to: 'sum', kind: 'message' },
      { from: 'sum', to: 'eff' }, { from: 'eff', to: 'mat' }, { from: 'mat', to: 'pub' },
      { from: 'pub', to: 'award' }, { from: 'award', to: 'take', kind: 'message' }, { from: 'take', to: 'end' },
    ],
    walkthrough: [
      { node: 'sum', title: 'Пишите для того, кто не участвовал', body: 'Читатель практики — руководитель другого учреждения. Ему нужно понять суть за минуту и решить, применимо ли это у него.' },
      { node: 'eff', title: 'Цифры пилота, а не прогноз', body: 'Указывается фактический результат: «экономия 47 минут в день при прогнозе 45». Именно расхождение прогноза и факта вызывает доверие.' },
      { node: 'mat', title: 'Без материалов практику не повторят', body: 'Методические рекомендации, инструкция пользователя, программа обучения и типовой приказ — иначе внедрение упрётся в организационные вопросы.' },
      { node: 'award', title: 'Публичное признание автора', body: 'Нематериальное стимулирование — часть управленческого аппарата экосистемы наравне с материальным.' },
    ],
  },

  // ══════════════════════════════ РАЗРАБОТКА ═════════════════
  {
    id: 'dev-build', role: 'developer', scenario: 'initiative', group: 'Команда разработки и ЦТ',
    title: 'Разработка прототипа и Gate 3',
    description: 'Итеративное создание MVP по Agile с постоянной обратной связью от будущих пользователей.',
    sla: '4 спринта по 2 недели',
    lanes: [L.dev, L.dtszn, L.emp, L.supplier],
    nodes: [
      { id: 'st', type: 'message', lane: 'dev', col: 0, row: 0, label: 'Положительное решение Gate 2' },
      { id: 'proj', type: 'user', lane: 'dev', col: 1, row: 0, label: 'Создать проект и наполнить бэклог' },
      { id: 'po', type: 'user', lane: 'dtszn', col: 2, row: 0, label: 'Утвердить приоритеты спринта' },
      { id: 'sprint', type: 'user', lane: 'dev', col: 3, row: 0, label: 'Выполнить спринт — 2 недели' },
      { id: 'need', type: 'xor', lane: 'dev', col: 2, row: 1, label: 'Нужна внешняя компетенция?' },
      { id: 'vendor', type: 'user', lane: 'supplier', col: 3, row: 1, label: 'Предоставить компоненты и компетенции' },
      { id: 'demo', type: 'user', lane: 'dev', col: 4, row: 0, label: 'Демонстрация ключевым пользователям' },
      { id: 'fb', type: 'user', lane: 'emp', col: 5, row: 0, label: 'Дать обратную связь по прототипу' },
      { id: 'gw', type: 'xor', lane: 'dev', col: 6, row: 0, label: 'MVP готов к пилоту?' },
      { id: 'g3', type: 'xor', lane: 'dev', col: 7, row: 0, label: 'Gate 3 — решение продакт-менеджера' },
      { id: 'doc', type: 'user', lane: 'dev', col: 8, row: 0, label: 'Подготовить документацию и инструкции' },
      { id: 'end', type: 'end', lane: 'dev', col: 9, row: 0, label: 'Прототип передан на пилотирование' },
      { id: 'redir', type: 'end', lane: 'dev', col: 8, row: 1, label: 'Redirect: изменить функциональность' },
      { id: 'kill', type: 'end', lane: 'dev', col: 8, row: 2, label: 'Kill: остановить разработку' },
    ],
    flows: [
      { from: 'st', to: 'proj' }, { from: 'proj', to: 'po', kind: 'message' },
      { from: 'po', to: 'sprint', kind: 'message' },
      { from: 'proj', to: 'need' }, { from: 'need', to: 'vendor', label: 'да', kind: 'message' },
      { from: 'vendor', to: 'sprint', kind: 'message' },
      { from: 'sprint', to: 'demo' }, { from: 'demo', to: 'fb', kind: 'message' },
      { from: 'fb', to: 'gw', kind: 'message' },
      { from: 'gw', to: 'po', label: 'нет — следующий спринт' },
      { from: 'gw', to: 'g3', label: 'да' },
      { from: 'g3', to: 'doc', label: 'Go' }, { from: 'doc', to: 'end' },
      { from: 'g3', to: 'redir', label: 'Redirect' }, { from: 'g3', to: 'kill', label: 'Kill' },
    ],
    walkthrough: [
      { node: 'po', title: 'Заказчик участвует в каждом спринте', body: 'Представитель ДТСЗН в роли продакт-менеджера утверждает приоритеты. Это условие Agile-контракта: состав MVP определяется совместно, а не постфактум.' },
      { node: 'sprint', title: 'Четыре спринта по две недели', body: 'План разработки фиксируется при передаче инициативы. Доска задач, спринты и бэклог продукта ведутся прямо в платформе.' },
      { node: 'vendor', title: 'Поставщики подключаются точечно', body: 'Готовые компоненты, программные продукты и консалтинг — там, где разрабатывать с нуля дороже, чем взять существующее.' },
      { node: 'fb', title: 'Обратная связь до пилота, а не после', body: 'Промежуточные демонстрации будущим пользователям снимают риск обнаружить неудобство уже на пилоте, когда переделывать дорого.' },
      { node: 'g3', title: 'Критерии Gate 3', body: 'Достигнутые цели спринтов, наличие рабочего MVP, положительная обратная связь на демонстрациях. Решение принимает продакт-менеджер.' },
    ],
  },

  // ══════════════════════════════ ПОСТАВЩИК ══════════════════
  {
    id: 'supplier', role: 'supplier', scenario: 'initiative', group: 'Поставщик технологий и услуг',
    title: 'Участие поставщика в проекте',
    description: 'Предоставление готовых компонентов, технологий и компетенций для создания и пилотирования прототипа.',
    lanes: [L.dev, L.supplier, L.dtszn],
    nodes: [
      { id: 'st', type: 'message', lane: 'dev', col: 0, row: 0, label: 'В проекте нужна внешняя компетенция' },
      { id: 'req', type: 'user', lane: 'dev', col: 1, row: 0, label: 'Сформулировать требование к компоненту' },
      { id: 'see', type: 'user', lane: 'supplier', col: 2, row: 0, label: 'Изучить инициативу на этапе разработки' },
      { id: 'gw', type: 'xor', lane: 'supplier', col: 3, row: 0, label: 'Есть подходящее решение?' },
      { id: 'no', type: 'end', lane: 'supplier', col: 4, row: 1, label: 'Отказ — команда ищет другой вариант' },
      { id: 'offer', type: 'user', lane: 'supplier', col: 4, row: 0, label: 'Предложить компонент или услугу' },
      { id: 'appr', type: 'user', lane: 'dtszn', col: 5, row: 0, label: 'Согласовать условия и ресурсы' },
      { id: 'deliver', type: 'user', lane: 'supplier', col: 6, row: 0, label: 'Передать компонент и сопровождать интеграцию' },
      { id: 'test', type: 'user', lane: 'dev', col: 7, row: 0, label: 'Встроить и проверить в составе прототипа' },
      { id: 'end', type: 'end', lane: 'dev', col: 8, row: 0, label: 'Компонент работает в составе решения' },
    ],
    flows: [
      { from: 'st', to: 'req' }, { from: 'req', to: 'see', kind: 'message' }, { from: 'see', to: 'gw' },
      { from: 'gw', to: 'offer', label: 'да' }, { from: 'gw', to: 'no', label: 'нет' },
      { from: 'offer', to: 'appr', kind: 'message' }, { from: 'appr', to: 'deliver', kind: 'message' },
      { from: 'deliver', to: 'test', kind: 'message' }, { from: 'test', to: 'end' },
    ],
    walkthrough: [
      { node: 'see', title: 'Видимость ограничена этапом', body: 'Поставщику доступны инициативы, дошедшие до разработки и пилотирования. Ранние идеи сотрудников остаются внутри Департамента.' },
      { node: 'appr', title: 'Условия согласует заказчик', body: 'Ресурсы и условия подтверждает центральный аппарат ДТСЗН — это исключает договорённости в обход владельца бюджета.' },
      { node: 'deliver', title: 'Не только передача, но и сопровождение', body: 'Поставщик отвечает за интеграцию компонента в прототип, а не только за его поставку.' },
    ],
  },

  // ══════════════════════════════ ПИЛОТЫ ═════════════════════
  {
    id: 'pilot-run', role: 'pilot_coordinator', scenario: 'initiative', group: 'Координатор пилотных площадок',
    title: 'Организация пилота и Gate 4',
    description: 'Проверка прототипа в реальных условиях со сбором доказательной базы: KPI, отклики сотрудников и граждан.',
    sla: '1 месяц пилота + 1 неделя анализа',
    lanes: [L.dev, L.pilot, L.head, L.emp],
    nodes: [
      { id: 'st', type: 'message', lane: 'dev', col: 0, row: 0, label: 'Прототип прошёл Gate 3' },
      { id: 'apps', type: 'user', lane: 'pilot', col: 1, row: 0, label: 'Рассмотреть заявки учреждений на площадку' },
      { id: 'pick', type: 'user', lane: 'pilot', col: 2, row: 0, label: 'Выбрать площадку и утвердить план' },
      { id: 'kpi', type: 'user', lane: 'pilot', col: 3, row: 0, label: 'Задать KPI: база, цель, направление улучшения' },
      { id: 'train', type: 'user', lane: 'head', col: 4, row: 0, label: 'Обучить сотрудников до старта' },
      { id: 'run', type: 'user', lane: 'emp', col: 5, row: 0, label: 'Применять решение в работе — 1 месяц' },
      { id: 'watch', type: 'service', lane: 'pilot', col: 6, row: 0, label: 'Еженедельно снимать показатели' },
      { id: 'crit', type: 'xor', lane: 'pilot', col: 6, row: 1, label: 'Критический сбой?' },
      { id: 'stop', type: 'end', lane: 'pilot', col: 7, row: 1, label: 'Досрочная остановка пилота' },
      { id: 'survey', type: 'user', lane: 'emp', col: 7, row: 0, label: 'Заполнить опрос по итогам' },
      { id: 'nlp', type: 'service', lane: 'pilot', col: 8, row: 0, label: 'Разобрать отклики и сопоставить с KPI' },
      { id: 'gw', type: 'xor', lane: 'pilot', col: 9, row: 0, label: 'Gate 4 — эффект доказан?' },
      { id: 'go', type: 'end', lane: 'pilot', col: 10, row: 0, label: 'Go: передано на решение о масштабировании' },
      { id: 'redir', type: 'end', lane: 'pilot', col: 10, row: 1, label: 'Redirect: доработка и повторный пилот' },
      { id: 'kill', type: 'end', lane: 'pilot', col: 10, row: 2, label: 'Kill: эффект не подтвердился' },
    ],
    flows: [
      { from: 'st', to: 'apps', kind: 'message' }, { from: 'apps', to: 'pick' }, { from: 'pick', to: 'kpi' },
      { from: 'kpi', to: 'train', kind: 'message' }, { from: 'train', to: 'run', kind: 'message' },
      { from: 'run', to: 'watch', kind: 'message' }, { from: 'watch', to: 'crit' },
      { from: 'crit', to: 'stop', label: 'да' },
      { from: 'watch', to: 'survey', kind: 'message' },
      { from: 'survey', to: 'nlp', kind: 'message' }, { from: 'nlp', to: 'gw' },
      { from: 'gw', to: 'go', label: 'Go' }, { from: 'gw', to: 'redir', label: 'Redirect' },
      { from: 'gw', to: 'kill', label: 'Kill' },
    ],
    walkthrough: [
      { node: 'apps', title: 'Площадки вызываются, а не назначаются', body: 'Учреждения сами заявляют готовность. Мотивированная площадка даёт качественную обратную связь, назначенная — формальные отписки.' },
      { node: 'kpi', title: 'KPI приходят из заявленного эффекта', body: 'Показатели не выдумываются заново: берётся то, что автор обещал на этапе подачи, с базовым и целевым значением.' },
      { node: 'train', title: 'Обучение до старта, не в первый день', body: 'Иначе первая неделя уходит на освоение и искажает статистику всего пилота.' },
      { node: 'crit', title: 'Критерий остановки — заранее', body: 'Договоритесь до старта, что считается критическим сбоем. Иначе спор о продолжении возникнет в самый неподходящий момент.' },
      { node: 'gw', title: 'Четыре критерия Gate 4', body: 'Доказанность заявленного эффекта, удовлетворённость пользователей, отсутствие критических проблем, соответствие требованиям безопасности и конфиденциальности.' },
    ],
  },

  // ══════════════════════════════ ДТСЗН ══════════════════════
  {
    id: 'dtszn-scale', role: 'dtszn', scenario: 'initiative', group: 'ДТСЗН (центральный аппарат)',
    title: 'Решение о масштабировании и тиражирование',
    description: 'Превращение подтверждённого на пилоте решения в изменение по всей сети учреждений.',
    sla: 'начало в течение 2 недель',
    lanes: [L.pilot, L.dtszn, L.head, L.sys],
    nodes: [
      { id: 'st', type: 'message', lane: 'pilot', col: 0, row: 0, label: 'Пилот завершён с решением Go' },
      { id: 'rev', type: 'user', lane: 'dtszn', col: 1, row: 0, label: 'Проверить подтверждённый эффект и данные пилота' },
      { id: 'ready', type: 'user', lane: 'dtszn', col: 2, row: 0, label: 'Оценить готовность учреждений и ресурсы' },
      { id: 'gw', type: 'xor', lane: 'dtszn', col: 3, row: 0, label: 'Gate 5 — масштабировать?' },
      { id: 'keep', type: 'end', lane: 'dtszn', col: 4, row: 1, label: 'Kill: сохранить как практику без тиражирования' },
      { id: 'plan', type: 'user', lane: 'dtszn', col: 4, row: 0, label: 'Утвердить план тиражирования и ресурсы' },
      { id: 'timer', type: 'timer', lane: 'dtszn', col: 5, row: 0, label: 'Начать в течение 2 недель' },
      { id: 'mat', type: 'user', lane: 'dtszn', col: 6, row: 0, label: 'Подготовить методические материалы и обучение' },
      { id: 'roll', type: 'user', lane: 'head', col: 7, row: 0, label: 'Внедрить решение в учреждении' },
      { id: 'mon', type: 'service', lane: 'sys', col: 8, row: 0, label: 'Отслеживать ход внедрения по учреждениям' },
      { id: 'val', type: 'service', lane: 'sys', col: 9, row: 0, label: 'Пересчитать валоризацию эффекта' },
      { id: 'end', type: 'end', lane: 'dtszn', col: 10, row: 0, label: 'Улучшение работает в масштабе города' },
    ],
    flows: [
      { from: 'st', to: 'rev', kind: 'message' }, { from: 'rev', to: 'ready' }, { from: 'ready', to: 'gw' },
      { from: 'gw', to: 'plan', label: 'Go' }, { from: 'gw', to: 'keep', label: 'Kill' },
      { from: 'plan', to: 'timer' }, { from: 'timer', to: 'mat' },
      { from: 'mat', to: 'roll', kind: 'message' }, { from: 'roll', to: 'mon', kind: 'message' },
      { from: 'mon', to: 'val' }, { from: 'val', to: 'end', kind: 'message' },
    ],
    walkthrough: [
      { node: 'rev', title: 'Решение опирается на данные пилота', body: 'Не на убеждённость авторов и не на симпатию к идее: только фактические KPI и отклики участников.' },
      { node: 'gw', title: 'Kill здесь не отменяет ценность', body: 'Решение может быть полезным локально, но не требовать централизованного тиражирования. Тогда оно остаётся в библиотеке практик для добровольного внедрения.' },
      { node: 'timer', title: 'Срок начала тиражирования', body: 'Две недели после решения. Затягивание на этом этапе — самый заметный для сотрудников признак бюрократического застоя.' },
      { node: 'val', title: 'Эффект пересчитывается в масштабе', body: 'Экономия одного учреждения умножается на число внедривших. Так локальные 47 минут в день превращаются в 21 тысячу человеко-часов в год.' },
    ],
  },
  {
    id: 'dtszn-sla', role: 'dtszn', scenario: 'initiative', group: 'ДТСЗН (центральный аппарат)',
    title: 'Контроль SLA и эскалация',
    description: 'Противодействие главному риску экосистемы — бюрократическому застою, когда сроки игнорируются из-за загрузки персонала.',
    lanes: [L.sys, L.dtszn, L.head],
    nodes: [
      { id: 'st', type: 'timer', lane: 'sys', col: 0, row: 0, label: 'Фоновая проверка каждые 15 минут' },
      { id: 'scan', type: 'service', lane: 'sys', col: 1, row: 0, label: 'Сверить сроки всех активных инициатив' },
      { id: 'gw', type: 'xor', lane: 'sys', col: 2, row: 0, label: 'Срок нарушен?' },
      { id: 'ok', type: 'end', lane: 'sys', col: 3, row: 1, label: 'Все решения в рамках срока' },
      { id: 'esc', type: 'service', lane: 'sys', col: 3, row: 0, label: 'Перевести задачу в статус эскалации' },
      { id: 'notify', type: 'message', lane: 'dtszn', col: 4, row: 0, label: 'Уведомление координатору экосистемы' },
      { id: 'analyse', type: 'user', lane: 'dtszn', col: 5, row: 0, label: 'Разобрать причину задержки' },
      { id: 'cause', type: 'xor', lane: 'dtszn', col: 6, row: 0, label: 'Причина задержки' },
      { id: 'push', type: 'user', lane: 'head', col: 7, row: 0, label: 'Принять решение по инициативе' },
      { id: 'res', type: 'user', lane: 'dtszn', col: 7, row: 1, label: 'Выделить ресурсы или экспертизу' },
      { id: 'norm', type: 'user', lane: 'dtszn', col: 7, row: 2, label: 'Пересмотреть норматив срока в настройках' },
      { id: 'audit', type: 'service', lane: 'sys', col: 8, row: 0, label: 'Зафиксировать в журнале аудита' },
      { id: 'end', type: 'end', lane: 'sys', col: 9, row: 0, label: 'Задержка устранена, причина учтена' },
    ],
    flows: [
      { from: 'st', to: 'scan' }, { from: 'scan', to: 'gw' },
      { from: 'gw', to: 'esc', label: 'да' }, { from: 'gw', to: 'ok', label: 'нет' },
      { from: 'esc', to: 'notify', kind: 'message' }, { from: 'notify', to: 'analyse' },
      { from: 'analyse', to: 'cause' },
      { from: 'cause', to: 'push', label: 'загрузка' },
      { from: 'cause', to: 'res', label: 'нехватка ресурсов' },
      { from: 'cause', to: 'norm', label: 'норматив занижен' },
      { from: 'push', to: 'audit', kind: 'message' },
      { from: 'res', to: 'audit', kind: 'message' }, { from: 'norm', to: 'audit', kind: 'message' },
      { from: 'audit', to: 'end' },
    ],
    walkthrough: [
      { node: 'st', title: 'Контроль не требует участия человека', body: 'Проверка запускается сама. Это принципиально: контроль, зависящий от того, вспомнил ли кто-то проверить, не работает.' },
      { node: 'gw', title: 'Срок считается в рабочих днях', body: 'Три рабочих дня от пятницы истекают в среду. Календарные сроки применяются только там, где ТЗ задаёт их явно — например, месяц пилота.' },
      { node: 'cause', title: 'Разбирается причина, а не факт', body: 'Просрочка может означать перегрузку ответственного, нехватку экспертизы или заниженный норматив. Реакция на каждую причину разная.' },
      { node: 'norm', title: 'Норматив можно изменить', body: 'Если срок систематически нарушается всеми, проблема в нормативе. Он правится в настройках процесса без участия разработчиков.' },
      { node: 'audit', title: 'Всё попадает в неизменяемый журнал', body: 'Записи связаны цепочкой хэшей: подмена или удаление задним числом ломает цепочку и выявляется проверкой целостности.' },
    ],
  },
  {
    id: 'dtszn-config', role: 'dtszn', scenario: 'initiative', group: 'ДТСЗН (центральный аппарат)',
    title: 'Настройка процесса без участия разработчиков',
    description: 'Адаптация конвейера к меняющимся условиям: этапы, сроки, критерии и ответственные роли задаются как данные.',
    lanes: [L.dtszn, L.sys],
    nodes: [
      { id: 'st', type: 'start', lane: 'dtszn', col: 0, row: 0, label: 'Аналитика показала узкое место процесса' },
      { id: 'find', type: 'user', lane: 'dtszn', col: 1, row: 0, label: 'Определить этап и характер проблемы' },
      { id: 'gw', type: 'xor', lane: 'dtszn', col: 2, row: 0, label: 'Что менять?' },
      { id: 'sla', type: 'user', lane: 'dtszn', col: 3, row: 0, label: 'Изменить срок и единицу измерения' },
      { id: 'crit', type: 'user', lane: 'dtszn', col: 3, row: 1, label: 'Скорректировать критерии Gate' },
      { id: 'role', type: 'user', lane: 'dtszn', col: 3, row: 2, label: 'Сменить ответственную роль' },
      { id: 'dec', type: 'user', lane: 'dtszn', col: 3, row: 3, label: 'Изменить перечень допустимых решений' },
      { id: 'save', type: 'service', lane: 'sys', col: 4, row: 0, label: 'Применить конфигурацию немедленно' },
      { id: 'audit', type: 'service', lane: 'sys', col: 5, row: 0, label: 'Записать изменение в журнал аудита' },
      { id: 'watch', type: 'user', lane: 'dtszn', col: 6, row: 0, label: 'Наблюдать за показателями этапа' },
      { id: 'end', type: 'end', lane: 'dtszn', col: 7, row: 0, label: 'Процесс адаптирован к реальным условиям' },
    ],
    flows: [
      { from: 'st', to: 'find' }, { from: 'find', to: 'gw' },
      { from: 'gw', to: 'sla', label: 'срок' }, { from: 'gw', to: 'crit', label: 'критерии' },
      { from: 'gw', to: 'role', label: 'ответственный' }, { from: 'gw', to: 'dec', label: 'решения' },
      { from: 'sla', to: 'save', kind: 'message' }, { from: 'crit', to: 'save', kind: 'message' },
      { from: 'role', to: 'save', kind: 'message' }, { from: 'dec', to: 'save', kind: 'message' },
      { from: 'save', to: 'audit' }, { from: 'audit', to: 'watch', kind: 'message' }, { from: 'watch', to: 'end' },
    ],
    walkthrough: [
      { node: 'st', title: 'Изменение начинается с данных', body: 'Не с ощущения, что «процесс неудобный», а с показателя: соблюдение SLA на конкретном этапе упало, или большинство инициатив останавливается на одной точке.' },
      { node: 'gw', title: 'Четыре рычага настройки', body: 'Срок, критерии, ответственная роль и перечень допустимых решений. Этого достаточно, чтобы перестроить процесс без изменения кода.' },
      { node: 'save', title: 'Изменения вступают в силу сразу', body: 'Новая конфигурация применяется к инициативам, которые придут на этот этап далее. Уже принятые решения не пересчитываются.' },
      { node: 'watch', title: 'Настройка — это цикл, а не разовое действие', body: 'После изменения смотрите на тот же показатель через несколько недель. Экосистема должна постоянно самооцениваться и адаптироваться.' },
    ],
  },

  // ══════════════ СЦЕНАРИЙ 2: ОБСУЖДЕНИЕ ИДЕЙ ═══════════════
  {
    id: 'ideas-e2e', role: 'all', scenario: 'ideas', group: 'Сквозной путь идеи',
    title: 'Полный путь: от проблемы до решения и признания вклада',
    description: 'Быстрый вход в экосистему. Сотрудник описывает проблему за минуту, коллеги предлагают решения, ревью отбирает полезное, модератор подтверждает, а вклад советчика превращается в очки и рекомендацию к поощрению.',
    lanes: [L.emp, L.adv, L.rev, L.mod, L.head, L.sys],
    nodes: [
      { id: 'st', type: 'start', lane: 'emp', col: 0, row: 0, label: 'Проблема мешает в ежедневной работе' },
      { id: 'quick', type: 'user', lane: 'emp', col: 1, row: 0, label: 'Подать идею за минуту: проблема и желаемый результат' },
      { id: 'dup', type: 'service', lane: 'sys', col: 2, row: 0, label: 'Показать похожие идеи до отправки' },
      { id: 'check', type: 'user', lane: 'mod', col: 3, row: 0, label: 'Проверить: понятность, дубли, персональные данные' },
      { id: 'gmod', type: 'xor', lane: 'mod', col: 4, row: 0, label: 'Решение модератора' },
      { id: 'rej', type: 'end', lane: 'mod', col: 4, row: 1, label: 'Отклонена или объединена с дублем' },
      { id: 'open', type: 'message', lane: 'adv', col: 5, row: 0, label: 'Идея открыта для решений' },
      { id: 'propose', type: 'user', lane: 'adv', col: 6, row: 0, label: 'Предложить решение или описать проверенный опыт' },
      { id: 'swipe', type: 'user', lane: 'rev', col: 7, row: 0, label: 'Оценить карточки предложений в быстром ревью' },
      { id: 'rank', type: 'service', lane: 'sys', col: 8, row: 0, label: 'Пересчитать полезность, собрать топ предложений' },
      { id: 'pick', type: 'user', lane: 'emp', col: 9, row: 0, label: 'Отметить решение, которое действительно помогло' },
      { id: 'verify', type: 'user', lane: 'mod', col: 10, row: 0, label: 'Подтвердить проверенный опыт' },
      { id: 'points', type: 'service', lane: 'sys', col: 11, row: 0, label: 'Начислить очки советчику по правилам модуля' },
      { id: 'gproj', type: 'xor', lane: 'mod', col: 12, row: 0, label: 'Требуется проект?' },
      { id: 'promote', type: 'user', lane: 'mod', col: 13, row: 0, label: 'Поднять идею до инициативы Stage-Gate' },
      { id: 'local', type: 'user', lane: 'mod', col: 13, row: 1, label: 'Применить решение силами учреждения' },
      { id: 'reward', type: 'user', lane: 'head', col: 14, row: 0, label: 'Рассмотреть рекомендацию к поощрению' },
      { id: 'fin', type: 'end', lane: 'head', col: 15, row: 0, label: 'Проблема решена, вклад советчика признан' },
    ],
    flows: [
      { from: 'st', to: 'quick' }, { from: 'quick', to: 'dup', kind: 'message' },
      { from: 'dup', to: 'check', kind: 'message' }, { from: 'check', to: 'gmod' },
      { from: 'gmod', to: 'rej', label: 'отклонить' }, { from: 'gmod', to: 'open', label: 'принять' },
      { from: 'open', to: 'propose' }, { from: 'propose', to: 'swipe', kind: 'message' },
      { from: 'swipe', to: 'rank', kind: 'message' }, { from: 'rank', to: 'pick', kind: 'message' },
      { from: 'pick', to: 'verify' }, { from: 'verify', to: 'points', kind: 'message' },
      { from: 'points', to: 'gproj' },
      { from: 'gproj', to: 'promote', label: 'нужен проект' }, { from: 'gproj', to: 'local', label: 'хватает решения' },
      { from: 'promote', to: 'reward' }, { from: 'local', to: 'reward' }, { from: 'reward', to: 'fin' },
    ],
    walkthrough: [
      { node: 'st', title: 'Порог входа — одна минута', body: 'Второй путь платформы существует ради тех проблем, которые не тянут на проект, но мешают каждый день. Сотрудник не оформляет инициативу — он просто описывает, что не так.' },
      { node: 'quick', title: 'Три поля вместо формы', body: 'Название, проблема и желаемый результат. Решение писать не нужно: его предложат коллеги, и чем свободнее сформулирована проблема, тем больше вариантов придёт.' },
      { node: 'dup', title: 'Дубли отсекаются на входе', body: 'Пока автор пишет, система показывает похожие идеи со степенью совпадения. Присоединиться к существующей выгоднее: решение найдётся быстрее, чем по двум разрозненным.' },
      { node: 'gmod', title: 'Модерация до публикации', body: 'Идея открывается для решений только после проверки. Это защита от спама и гарантия того, что очки начисляются за осмысленный вклад. Режим отключается администратором.' },
      { node: 'propose', title: 'Два вида вклада', body: 'Предложение — гипотеза «так можно сделать». Проверенный опыт — «у нас это уже работает, вот результат». Опыт подтверждает модератор, и он ценится выше.' },
      { node: 'swipe', title: 'Ревью распределяет внимание', body: 'Коллеги листают карточки с телефона и отмечают то, что выглядит рабочим. Оценки не начисляют очки автору — они лишь поднимают полезное наверх, поэтому накрутка бессмысленна.' },
      { node: 'pick', title: 'Последнее слово за автором идеи', body: 'Только он знает, что действительно помогло. Его отметка «полезно» — единственная оценка, которая напрямую превращается в очки советчику.' },
      { node: 'gproj', title: 'Развилка двух путей платформы', body: 'Если решение требует разработки и пилота — идея поднимается до инициативы и уходит в конвейер Stage-Gate. Если хватает организационных мер — учреждение применяет решение само.' },
      { node: 'reward', title: 'Система предлагает, решает человек', body: 'По итогам периода руководитель получает список сотрудников с наибольшим вкладом и подходящие меры поощрения. Автоматической выдачи нет — решение принимает руководитель.' },
    ],
  },
  {
    id: 'idea-quick', role: 'employee', scenario: 'ideas', group: 'Сотрудник учреждения',
    title: 'Подать идею за минуту',
    description: 'Форма из трёх обязательных полей с быстрыми шаблонами, автосохранением черновика и подсказкой о похожих идеях. Критерий приёмки — подача не дольше 60 секунд.',
    sla: 'подача — не более 60 секунд',
    lanes: [L.emp, L.sys],
    nodes: [
      { id: 'st', type: 'start', lane: 'emp', col: 0, row: 0, label: 'Проблема мешает работать прямо сейчас' },
      { id: 'tpl', type: 'user', lane: 'emp', col: 1, row: 0, label: 'Выбрать быстрый шаблон подачи' },
      { id: 'fill', type: 'user', lane: 'emp', col: 2, row: 0, label: 'Заполнить три поля: суть, проблема, результат' },
      { id: 'draft', type: 'service', lane: 'sys', col: 3, row: 1, label: 'Сохранять черновик автоматически' },
      { id: 'sim', type: 'service', lane: 'sys', col: 3, row: 0, label: 'Показать похожие идеи со степенью совпадения' },
      { id: 'gdup', type: 'xor', lane: 'emp', col: 4, row: 0, label: 'Такая идея уже есть?' },
      { id: 'join', type: 'user', lane: 'emp', col: 5, row: 1, label: 'Открыть чужую идею и добавить свой контекст' },
      { id: 'joinend', type: 'end', lane: 'emp', col: 6, row: 1, label: 'Усилия объединены, дубль не создан' },
      { id: 'send', type: 'user', lane: 'emp', col: 5, row: 0, label: 'Опубликовать идею' },
      { id: 'route', type: 'service', lane: 'sys', col: 6, row: 0, label: 'Присвоить номер IDEA и направить модератору' },
      { id: 'wait', type: 'timer', lane: 'emp', col: 7, row: 0, label: 'Ожидание проверки модератором' },
      { id: 'end', type: 'end', lane: 'emp', col: 8, row: 0, label: 'Идея открыта — коллеги предлагают решения' },
    ],
    flows: [
      { from: 'st', to: 'tpl' }, { from: 'tpl', to: 'fill' },
      { from: 'fill', to: 'sim', kind: 'message' }, { from: 'fill', to: 'draft', kind: 'message' },
      { from: 'sim', to: 'gdup', kind: 'message' },
      { from: 'gdup', to: 'join', label: 'да' }, { from: 'join', to: 'joinend' },
      { from: 'gdup', to: 'send', label: 'нет' },
      { from: 'send', to: 'route', kind: 'message' }, { from: 'route', to: 'wait', kind: 'message' },
      { from: 'wait', to: 'end' },
    ],
    walkthrough: [
      { node: 'tpl', title: 'Шаблон снимает страх чистого листа', body: 'Пять типовых situations: улучшить интерфейс, ускорить процесс, уменьшить ошибки, автоматизировать действие, другое. Шаблон подставляет формулировки и направление.' },
      { node: 'fill', title: 'Обязательных полей ровно три', body: 'Суть, проблема, желаемый результат. Категория, срочность, ссылки и место в системе скрыты под «Уточнениями» — их можно заполнить позже или не заполнять вовсе.' },
      { node: 'draft', title: 'Черновик не теряется', body: 'Форма сохраняется автоматически каждые полторы секунды. Если вкладка закрылась или сотрудника отвлекли, написанное восстанавливается одной кнопкой.' },
      { node: 'sim', title: 'Подсказка вместо запрета', body: 'Система не блокирует похожую идею, а показывает совпадения и даёт решить самому. Порог намеренно невысокий: пропущенный дубль дороже лишней подсказки.' },
      { node: 'wait', title: 'Что происходит после отправки', body: 'Идея получает номер вида IDEA-2026-0001 и уходит модератору. Автор получает уведомление о решении, а после принятия — очки за прохождение модерации.' },
    ],
  },
  {
    id: 'adv-propose', role: 'employee', scenario: 'ideas', group: 'Советчик',
    title: 'Предложить решение или поделиться опытом',
    description: 'Роль советчика: две минуты на описание того, что сработало у вас. Половина проблем в учреждениях уже кем-то решена — модуль существует, чтобы об этом узнали остальные.',
    sla: 'предложение — не более 2 минут',
    lanes: [L.adv, L.sys, L.emp, L.mod],
    nodes: [
      { id: 'st', type: 'message', lane: 'adv', col: 0, row: 0, label: 'Идея коллеги открыта для решений' },
      { id: 'read', type: 'user', lane: 'adv', col: 1, row: 0, label: 'Прочитать проблему и уже предложенные решения' },
      { id: 'gkind', type: 'xor', lane: 'adv', col: 2, row: 0, label: 'Что вы вносите?' },
      { id: 'prop', type: 'user', lane: 'adv', col: 3, row: 0, label: 'Предложение: так можно сделать' },
      { id: 'exp', type: 'user', lane: 'adv', col: 3, row: 1, label: 'Проверенный опыт: у нас это уже работает' },
      { id: 'dupchk', type: 'service', lane: 'sys', col: 4, row: 0, label: 'Сравнить с уже предложенным по этой идее' },
      { id: 'gdup', type: 'xor', lane: 'sys', col: 5, row: 0, label: 'Совпадает с существующим?' },
      { id: 'support', type: 'user', lane: 'adv', col: 6, row: 1, label: 'Подтвердить существующее решение вместо дубля' },
      { id: 'pub', type: 'service', lane: 'sys', col: 6, row: 0, label: 'Опубликовать и начислить очки за предложение' },
      { id: 'notify', type: 'message', lane: 'emp', col: 7, row: 0, label: 'Автор идеи получает уведомление' },
      { id: 'useful', type: 'user', lane: 'emp', col: 8, row: 0, label: 'Отметить решение полезным' },
      { id: 'ver', type: 'user', lane: 'mod', col: 8, row: 1, label: 'Подтвердить проверенный опыт' },
      { id: 'pts', type: 'service', lane: 'sys', col: 9, row: 0, label: 'Начислить очки: полезное решение, подтверждённый опыт' },
      { id: 'end', type: 'end', lane: 'adv', col: 10, row: 0, label: 'Вклад учтён в рейтинге советчика' },
    ],
    flows: [
      { from: 'st', to: 'read' }, { from: 'read', to: 'gkind' },
      { from: 'gkind', to: 'prop', label: 'гипотеза' }, { from: 'gkind', to: 'exp', label: 'опыт' },
      { from: 'prop', to: 'dupchk', kind: 'message' }, { from: 'exp', to: 'dupchk', kind: 'message' },
      { from: 'dupchk', to: 'gdup' },
      { from: 'gdup', to: 'support', label: 'да' }, { from: 'support', to: 'pts' },
      { from: 'gdup', to: 'pub', label: 'нет' },
      { from: 'pub', to: 'notify', kind: 'message' },
      { from: 'notify', to: 'useful' }, { from: 'useful', to: 'pts', kind: 'message' },
      { from: 'exp', to: 'ver', kind: 'message' }, { from: 'ver', to: 'pts', kind: 'message' },
      { from: 'pts', to: 'end', kind: 'message' },
    ],
    walkthrough: [
      { node: 'read', title: 'Сначала — что уже предложено', body: 'Решения на странице идеи отсортированы: сверху внедрённые и подтверждённые. Если ваша мысль уже высказана, полезнее подтвердить её, чем повторить своими словами.' },
      { node: 'gkind', title: 'Гипотеза и опыт различаются намеренно', body: 'Предложение оплачивается сразу после публикации, проверенный опыт — только после подтверждения модератором, зато выше. Так у платформы появляется стимул делиться доказанным, а не правдоподобным.' },
      { node: 'dupchk', title: 'Дубль отсекается при отправке', body: 'Текст сравнивается с уже опубликованными по этой идее. При высоком совпадении публикация отклоняется с предложением подтвердить существующее решение — очки за копию не начисляются.' },
      { node: 'useful', title: 'Отметку ставит только автор идеи', body: 'Он единственный знает, что действительно помогло. Свою собственную идею отметить нельзя, отметка необратима — поэтому она и стоит дороже лайка в ревью.' },
      { node: 'pts', title: 'Очки — за помощь коллегам, не за активность', body: 'Начисление за предложение к своей же идее не производится. Дубли, самооценки и повторные начисления отсекаются, а модератор может отменить любое начисление с указанием причины.' },
    ],
  },
  {
    id: 'adv-review', role: 'employee', scenario: 'ideas', group: 'Советчик',
    title: 'Быстрое ревью предложений',
    description: 'Оценка чужих решений карточками — с телефона, одним движением. Ревью отбирает полезное без чтения всех обсуждений и не даёт ни одному предложению остаться незамеченным.',
    sla: 'оценка карточки — несколько секунд',
    lanes: [L.rev, L.sys, L.mod],
    nodes: [
      { id: 'st', type: 'start', lane: 'rev', col: 0, row: 0, label: 'Есть несколько свободных минут' },
      { id: 'open', type: 'user', lane: 'rev', col: 1, row: 0, label: 'Открыть «Ревью предложений» с телефона' },
      { id: 'filter', type: 'user', lane: 'rev', col: 2, row: 0, label: 'При необходимости сузить очередь фильтрами' },
      { id: 'queue', type: 'service', lane: 'sys', col: 3, row: 0, label: 'Подобрать карточку, которую видели реже всего' },
      { id: 'read', type: 'user', lane: 'rev', col: 4, row: 0, label: 'Прочитать суть решения и ожидаемый эффект' },
      { id: 'gact', type: 'xor', lane: 'rev', col: 5, row: 0, label: 'Как оценить?' },
      { id: 'like', type: 'user', lane: 'rev', col: 6, row: 0, label: 'Свайп вправо — «Полезно»' },
      { id: 'fav', type: 'user', lane: 'rev', col: 6, row: 1, label: 'Свайп вверх — «В избранное»' },
      { id: 'skip', type: 'user', lane: 'rev', col: 6, row: 2, label: 'Свайп влево — «Пропустить»' },
      { id: 'reason', type: 'user', lane: 'rev', col: 7, row: 2, label: 'Указать причину: неясно, дорого, рискованно, дубль' },
      { id: 'det', type: 'user', lane: 'rev', col: 6, row: 3, label: 'Тап по карточке — открыть подробности' },
      { id: 'guard', type: 'service', lane: 'sys', col: 8, row: 0, label: 'Проверить: не своё, не повторно, частота в норме' },
      { id: 'gfraud', type: 'xor', lane: 'sys', col: 9, row: 0, label: 'Похоже на накрутку?' },
      { id: 'flag', type: 'message', lane: 'mod', col: 9, row: 1, label: 'Сигнал антифрода модератору' },
      { id: 'save', type: 'service', lane: 'sys', col: 10, row: 0, label: 'Записать оценку, обновить полезность предложения' },
      { id: 'top', type: 'user', lane: 'mod', col: 11, row: 1, label: 'Разобрать топ предложений первыми' },
      { id: 'gmore', type: 'xor', lane: 'rev', col: 11, row: 0, label: 'Продолжаем?' },
      { id: 'end', type: 'end', lane: 'rev', col: 12, row: 0, label: 'Полезное поднялось наверх без чтения обсуждений' },
      { id: 'modend', type: 'end', lane: 'mod', col: 12, row: 1, label: 'Внимание модератора направлено на лучшее' },
    ],
    flows: [
      { from: 'st', to: 'open' }, { from: 'open', to: 'filter' },
      { from: 'filter', to: 'queue', kind: 'message' }, { from: 'queue', to: 'read', kind: 'message' },
      { from: 'read', to: 'gact' },
      { from: 'gact', to: 'like', label: 'вправо' }, { from: 'gact', to: 'fav', label: 'вверх' },
      { from: 'gact', to: 'skip', label: 'влево' }, { from: 'gact', to: 'det', label: 'тап' },
      { from: 'det', to: 'gact', label: 'вернуться' },
      { from: 'skip', to: 'reason' },
      { from: 'like', to: 'guard' }, { from: 'fav', to: 'guard' }, { from: 'reason', to: 'guard' },
      { from: 'guard', to: 'gfraud' },
      { from: 'gfraud', to: 'flag', label: 'да' }, { from: 'gfraud', to: 'save', label: 'нет' },
      { from: 'save', to: 'gmore' }, { from: 'save', to: 'top', kind: 'message' },
      { from: 'gmore', to: 'queue', label: 'следующая' }, { from: 'gmore', to: 'end', label: 'на сегодня хватит' },
      { from: 'top', to: 'modend' },
    ],
    walkthrough: [
      { node: 'open', title: 'Формат рассчитан на телефон', body: 'Одна карточка на экране, оценка одним движением. Раздел открывают в перерыве или по дороге — там, где читать длинное обсуждение никто не станет.' },
      { node: 'queue', title: 'Очередь распределяет внимание', body: 'Первыми показываются предложения, которые видели меньше всего. Так ни одно решение не остаётся неоценённым, а порядок не зависит от того, кто громче.' },
      { node: 'gact', title: 'Четыре действия и все они дублируются кнопками', body: 'Свайпы удобны на телефоне, но не всем и не везде. Кнопки «Полезно», «Пропустить», «В избранное» и «Подробнее» делают то же самое, а на компьютере работают стрелки и Enter.' },
      { node: 'fav', title: 'Избранное — сигнал модератору', body: '«Требует внимания» весит вдвое больше лайка и поднимает предложение в очереди разбора. Это способ сказать «посмотрите на это первым», не отклоняя и не одобряя.' },
      { node: 'reason', title: 'Причина пропуска необязательна', body: 'Отдельная причина автору не показывается — модератор видит их сводно. Шесть закрытых вариантов вместо свободного текста: так сигнал остаётся сравнимым между предложениями.' },
      { node: 'guard', title: 'Три ограничения на каждой оценке', body: 'Своё предложение в очередь не попадает, повторная оценка невозможна на уровне базы данных, частота ограничена настройкой. Ошибочный свайп отменяется возвратом к предыдущей карточке.' },
      { node: 'gfraud', title: 'Антифрод не наказывает, а сообщает', body: 'Серия слишком быстрых оценок или работа нескольких учётных записей с одного устройства поднимают сигнал модератору. Решение принимает человек: оценки могли быть быстрыми и по делу.' },
      { node: 'save', title: 'Почему лайки не дают очков', body: 'Оценка влияет только на полезность предложения и порядок показа. Очки начисляются после модерации, отметки автором идеи или внедрения — поэтому массовое пролистывание не превращается в рейтинг.' },
    ],
  },
  {
    id: 'mod-ideas', role: 'expert', scenario: 'ideas', group: 'Модератор модуля',
    title: 'Проверка идей, подтверждение опыта и контроль качества',
    description: 'Модератор отвечает за то, чтобы обсуждение оставалось осмысленным: проверяет идеи, подтверждает опыт, разбирает обращения и сигналы антифрода, отменяет необоснованные начисления.',
    lanes: [L.mod, L.sys, L.emp],
    nodes: [
      { id: 'st', type: 'message', lane: 'mod', col: 0, row: 0, label: 'В очереди модерации появилась работа' },
      { id: 'open', type: 'user', lane: 'mod', col: 1, row: 0, label: 'Открыть раздел модерации' },
      { id: 'gtype', type: 'xor', lane: 'mod', col: 2, row: 0, label: 'Что проверяем?' },
      { id: 'idea', type: 'user', lane: 'mod', col: 3, row: 0, label: 'Проверить идею: понятность, дубль, персональные данные' },
      { id: 'gidea', type: 'xor', lane: 'mod', col: 4, row: 0, label: 'Решение по идее' },
      { id: 'appr', type: 'service', lane: 'sys', col: 5, row: 0, label: 'Открыть для решений и начислить автору очки' },
      { id: 'clar', type: 'message', lane: 'emp', col: 5, row: 1, label: 'Запросить уточнение у автора' },
      { id: 'merge', type: 'user', lane: 'mod', col: 5, row: 2, label: 'Объединить с основной идеей' },
      { id: 'exp', type: 'user', lane: 'mod', col: 3, row: 3, label: 'Проверить опыт: применялся ли и дал ли результат' },
      { id: 'verify', type: 'service', lane: 'sys', col: 5, row: 3, label: 'Подтвердить: очки и знак отличия советчику' },
      { id: 'signal', type: 'user', lane: 'mod', col: 3, row: 4, label: 'Разобрать обращение или сигнал антифрода' },
      { id: 'revoke', type: 'service', lane: 'sys', col: 5, row: 4, label: 'Отменить начисление с указанием причины' },
      { id: 'audit', type: 'service', lane: 'sys', col: 6, row: 0, label: 'Записать действие в неизменяемый журнал' },
      { id: 'end', type: 'end', lane: 'mod', col: 7, row: 0, label: 'Обсуждение остаётся осмысленным' },
    ],
    flows: [
      { from: 'st', to: 'open' }, { from: 'open', to: 'gtype' },
      { from: 'gtype', to: 'idea', label: 'новая идея' },
      { from: 'gtype', to: 'exp', label: 'проверенный опыт' },
      { from: 'gtype', to: 'signal', label: 'обращение' },
      { from: 'idea', to: 'gidea' },
      { from: 'gidea', to: 'appr', label: 'принять' },
      { from: 'gidea', to: 'clar', label: 'уточнить' },
      { from: 'gidea', to: 'merge', label: 'дубль' },
      { from: 'exp', to: 'verify' }, { from: 'signal', to: 'revoke' },
      { from: 'appr', to: 'audit' }, { from: 'verify', to: 'audit' }, { from: 'revoke', to: 'audit' },
      { from: 'merge', to: 'audit', kind: 'message' },
      { from: 'audit', to: 'end' },
    ],
    walkthrough: [
      { node: 'gtype', title: 'Три очереди в одном разделе', body: 'Идеи на проверке, проверенный опыт и обращения с сигналами антифрода. Отдельная вкладка показывает топ предложений по итогам ревью, ещё одна — журнал начислений.' },
      { node: 'idea', title: 'Что проверяет модератор в идее', body: 'Понятна ли проблема, не дублирует ли уже поданную, нет ли в тексте персональных данных сверх необходимого. Содержательную ценность оценивают коллеги решениями, а не модератор.' },
      { node: 'gidea', title: 'Четыре исхода вместо «да/нет»', body: 'Принять к обсуждению, запросить уточнение, объединить с дублем, отклонить. Отклонение и уточнение требуют причины — она видна автору и попадает в карточку идеи.' },
      { node: 'verify', title: 'Подтверждение опыта — самое ценное действие', body: 'Оно превращает чей-то рабочий приём в проверенную практику: советчик получает больше всего очков и знак отличия, а другие учреждения — основание повторить.' },
      { node: 'revoke', title: 'Отмена начисления не стирает историю', body: 'Запись остаётся в журнале с указанием причины и автора отмены. Из рейтинга очки исключаются, но факт начисления и его отмены виден всегда.' },
      { node: 'audit', title: 'Полномочия уравновешены журналом', body: 'Модератор может многое, поэтому каждое его действие связано хэшем с предыдущей записью. Подмена задним числом ломает цепочку и выявляется проверкой целостности.' },
    ],
  },
  {
    id: 'head-reward', role: 'head', scenario: 'ideas', group: 'Руководитель учреждения',
    title: 'Рейтинг советчиков и рекомендации к поощрению',
    description: 'Вклад в решение чужих проблем измерим и потому может быть поощрён. Система формирует рекомендацию по итогам периода, решение принимает руководитель в рамках трудового законодательства.',
    sla: 'период — месяц, квартал или год',
    lanes: [L.head, L.sys, L.emp],
    nodes: [
      { id: 'st', type: 'timer', lane: 'head', col: 0, row: 0, label: 'Завершился отчётный период' },
      { id: 'build', type: 'service', lane: 'sys', col: 1, row: 0, label: 'Отобрать сотрудников выше порога очков' },
      { id: 'list', type: 'message', lane: 'head', col: 2, row: 0, label: 'Список рекомендаций к поощрению' },
      { id: 'rate', type: 'user', lane: 'head', col: 3, row: 0, label: 'Открыть рейтинг советчиков своего учреждения' },
      { id: 'review', type: 'user', lane: 'head', col: 4, row: 0, label: 'Проверить вклад: решения, опыт, внедрения' },
      { id: 'gdec', type: 'xor', lane: 'head', col: 5, row: 0, label: 'Решение по рекомендации' },
      { id: 'agree', type: 'user', lane: 'head', col: 6, row: 0, label: 'Согласовать и утвердить меру поощрения' },
      { id: 'rej', type: 'end', lane: 'head', col: 6, row: 1, label: 'Отклонено с указанием основания' },
      { id: 'fix', type: 'service', lane: 'sys', col: 7, row: 0, label: 'Зафиксировать статус и уведомить сотрудника' },
      { id: 'impl', type: 'user', lane: 'head', col: 8, row: 0, label: 'Реализовать меру в установленном порядке' },
      { id: 'know', type: 'message', lane: 'emp', col: 8, row: 1, label: 'Сотрудник видит признание вклада' },
      { id: 'end', type: 'end', lane: 'head', col: 9, row: 0, label: 'Полезное поведение подкреплено' },
    ],
    flows: [
      { from: 'st', to: 'build', kind: 'message' }, { from: 'build', to: 'list', kind: 'message' },
      { from: 'list', to: 'rate' }, { from: 'rate', to: 'review' }, { from: 'review', to: 'gdec' },
      { from: 'gdec', to: 'agree', label: 'поощрить' }, { from: 'gdec', to: 'rej', label: 'отклонить' },
      { from: 'agree', to: 'fix', kind: 'message' }, { from: 'fix', to: 'impl' },
      { from: 'fix', to: 'know', kind: 'message' },
      { from: 'impl', to: 'end' },
    ],
    walkthrough: [
      { node: 'build', title: 'Рекомендация формируется автоматически', body: 'Система отбирает сотрудников, набравших за период больше порогового числа очков, и подбирает меру по характеру вклада: внедрённое решение, подтверждённый опыт или первое место в рейтинге.' },
      { node: 'rate', title: 'Руководитель видит своих сотрудников', body: 'Рейтинг ограничен учреждением: сравнение идёт внутри одного коллектива. Организация может скрыть рейтинг от рядовых участников — тогда он остаётся доступен только руководителям и модераторам.' },
      { node: 'review', title: 'Очки — основание, а не приговор', body: 'Перед решением видно, из чего они сложились: сколько предложений, что признано полезным, что подтверждено и внедрено. Журнал начислений показывает каждое событие отдельно.' },
      { node: 'gdec', title: 'Система предлагает — решает человек', body: 'Автоматической выдачи поощрений нет. Рекомендация проходит статусы «Предложено», «Согласовано», «Утверждено», «Реализовано» либо отклоняется с указанием основания.' },
      { node: 'impl', title: 'Меры подобраны под государственную службу', body: 'Дополнительный выходной, компенсационный день отдыха, гибкое начало дня, благодарность, грамота, обучение, кадровый резерв, наставничество. Каждая мера сопровождается пометкой о правовых условиях применения.' },
    ],
  },
];

// ── Пользовательские пути ────────────────────────────────────
// Альбом делится на два сценария. Первый — конвейер Stage-Gate для проблем,
// требующих проекта. Второй — быстрый обмен решениями между сотрудниками.
// Роли модуля «Идеи и решения» не заводятся отдельными учётными записями:
// это функции, которые исполняют существующие роли платформы.
export const SCENARIOS = [
  {
    id: 'initiative',
    title: 'Пользовательские пути при подаче полноценной инициативы',
    short: 'Подача инициативы',
    lead: 'Проблема требует проекта: разработки, пилота, тиражирования.',
    description: 'Инициатива проходит шесть стадий и пять точек принятия решений. Работы отделены от решений: на каждой точке уполномоченный участник выбирает Go, Kill, Hold или Redirect на основе доказательств, и каждое решение документируется с обязательной аргументацией.',
    roles: [
      { role: 'employee', title: 'Сотрудник учреждения',
        does: 'Формулирует инициативу: проблема, предлагаемое решение, прогнозируемый эффект. Участвует в пилоте и даёт обратную связь, которая становится доказательной базой на Gate 4.' },
      { role: 'head', title: 'Руководитель учреждения',
        does: 'Принимает решение на Gate 1 за 3 рабочих дня: соответствие регламентам, потенциал локального улучшения, реалистичность в рамках бюджета. Подаёт заявку на роль пилотной площадки.' },
      { role: 'expert', title: 'Эксперт ДТСЗН',
        does: 'Проводит экспертизу на Gate 2 за 5 рабочих дней: стратегическая совместимость, потенциал масштабирования, ожидаемый эффект, техническая осуществимость. Публикует лучшие практики.' },
      { role: 'developer', title: 'Команда разработки и ЦТ',
        does: 'Создаёт MVP за 4 спринта по 2 недели, ведёт доску задач и техническую документацию, подтверждает готовность прототипа к пилоту на Gate 3.' },
      { role: 'supplier', title: 'Поставщик технологий и услуг',
        does: 'Подключается к инициативам, дошедшим до разработки: предоставляет технологии, участвует в сборке прототипа и его сопровождении.' },
      { role: 'pilot_coordinator', title: 'Координатор пилотных площадок',
        does: 'Ведёт пилот в учреждении месяц, отслеживает KPI с базовым, целевым и фактическим значением, собирает опросы сотрудников и граждан, выносит решение на Gate 4.' },
      { role: 'dtszn', title: 'ДТСЗН (центральный аппарат)',
        does: 'Принимает решение о масштабировании на Gate 5, организует обучение и методические материалы, контролирует SLA и настраивает конвейер без участия разработчиков.' },
    ],
  },
  {
    id: 'ideas',
    title: 'Пользовательские пути при обсуждении идей',
    short: 'Обсуждение идей',
    lead: 'Проблема мешает каждый день, но проекта не требует — решение уже есть у коллег.',
    description: 'Быстрый вход в экосистему: минута на описание проблемы, две минуты на предложение решения, несколько секунд на оценку чужого. Вклад советчиков измеряется очками и превращается в рекомендацию к поощрению. Идея, для которой нужен проект, поднимается до инициативы и переходит в первый сценарий.',
    roles: [
      { role: 'employee', title: 'Пользователь — автор идеи',
        does: 'Описывает проблему и желаемый результат за минуту. Читает предложенные решения и отмечает то, которое действительно помогло, — это единственная оценка, напрямую превращающаяся в очки советчику.' },
      { role: 'advisor', title: 'Советчик',
        does: 'Любой сотрудник, предлагающий решение чужой проблемы или описывающий проверенный опыт своего учреждения. Получает очки за предложение, отметку «полезно», подтверждение опыта и внедрение.' },
      { role: 'reviewer', title: 'Ревьюер',
        does: 'Любой сотрудник в режиме быстрого ревью: листает карточки предложений с телефона и отмечает «полезно», «пропустить» или «в избранное». Оценки поднимают полезное наверх, но очков автору не начисляют.' },
      { role: 'moderator', title: 'Модератор модуля (эксперт ДТСЗН)',
        does: 'Проверяет новые идеи, подтверждает проверенный опыт, объединяет дубли, разбирает обращения и сигналы антифрода, отменяет необоснованные начисления. Каждое действие попадает в неизменяемый журнал.' },
      { role: 'head', title: 'Руководитель учреждения',
        does: 'Видит рейтинг советчиков своего учреждения и список рекомендаций к поощрению. Согласовывает, утверждает или отклоняет меру — автоматической выдачи поощрений в системе нет.' },
      { role: 'dtszn', title: 'Администратор модуля (ДТСЗН)',
        does: 'Задаёт правила начисления очков, справочник мер поощрения, режим модерации, видимость рейтинга и пределы антифрода в ревью. Всё настраивается как данные, без изменения кода.' },
    ],
  },
];

export const scenarioOf = (id) => SCENARIOS.find((s) => s.id === id) || SCENARIOS[0];

export function diagramsForScenario(scenario) {
  return scenario ? DIAGRAMS.filter((d) => d.scenario === scenario) : DIAGRAMS;
}

export function diagramsForRole(role) {
  if (!role || role === 'all') return DIAGRAMS;
  return DIAGRAMS.filter((d) => d.role === role || d.role === 'all');
}

export const ROLE_ORDER = ['all', 'employee', 'head', 'expert', 'developer', 'supplier', 'pilot_coordinator', 'dtszn'];
