// Модели бизнес-процессов в нотации BPMN. Каждая схема описывает реальный процесс
// платформы: триггер, шаги участников и системы, точки принятия решений и SLA из ТЗ.
//
// col — колонка в сетке, row — строка внутри дорожки. Раскладка считается рендерером.

const L = {
  emp: { id: 'emp', title: 'Сотрудник учреждения' },
  head: { id: 'head', title: 'Руководитель учреждения' },
  expert: { id: 'expert', title: 'Эксперт ДТСЗН' },
  dev: { id: 'dev', title: 'Команда разработки и ЦТ' },
  supplier: { id: 'supplier', title: 'Поставщик' },
  pilot: { id: 'pilot', title: 'Координатор пилотов' },
  dtszn: { id: 'dtszn', title: 'ДТСЗН (центральный аппарат)' },
  sys: { id: 'sys', title: 'Платформа Social1' },
};

export const DIAGRAMS = [
  // ══════════════════════════════════════════════════════════
  {
    id: 'e2e', role: 'all', group: 'Сквозной процесс',
    title: 'Полный цикл: от проблемы до масштабирования',
    description: 'Инициатива проходит шесть стадий и пять точек принятия решений. Работы отделены от решений: на каждой точке ответственный участник выбирает Go, Kill, Hold или Redirect на основе доказательств.',
    lanes: [L.emp, L.head, L.expert, L.dev, L.pilot, L.dtszn],
    nodes: [
      { id: 'st', type: 'start', lane: 'emp', col: 0, row: 0, label: 'Обнаружена проблема в ежедневной работе' },
      { id: 'form', type: 'user', lane: 'emp', col: 1, row: 0, label: 'Сформулировать и подать инициативу' },
      { id: 'g1in', type: 'message', lane: 'head', col: 2, row: 0, label: 'Инициатива поступила руководителю' },
      { id: 'g1eval', type: 'user', lane: 'head', col: 3, row: 0, label: 'Оценить по критериям Gate 1' },
      { id: 'g1', type: 'xor', lane: 'head', col: 4, row: 0, label: 'Gate 1 — 3 рабочих дня' },
      { id: 'g1kill', type: 'end', lane: 'head', col: 4, row: 1, label: 'Kill: отказ с обоснованием' },
      { id: 'g2eval', type: 'user', lane: 'expert', col: 5, row: 0, label: 'Экспертиза: стратегия, масштабируемость, риски' },
      { id: 'g2', type: 'xor', lane: 'expert', col: 6, row: 0, label: 'Gate 2 — 5 рабочих дней' },
      { id: 'g2back', type: 'end', lane: 'expert', col: 6, row: 1, label: 'Kill / Redirect: возврат автору' },
      { id: 'build', type: 'user', lane: 'dev', col: 7, row: 0, label: 'Разработать MVP: 4 спринта по 2 недели' },
      { id: 'g3', type: 'xor', lane: 'dev', col: 8, row: 0, label: 'Gate 3 — готовность прототипа' },
      { id: 'run', type: 'user', lane: 'pilot', col: 9, row: 0, label: 'Провести пилот в учреждении — 1 месяц' },
      { id: 'fb', type: 'service', lane: 'pilot', col: 10, row: 0, label: 'Собрать обратную связь и KPI — 1 неделя' },
      { id: 'g4', type: 'xor', lane: 'pilot', col: 11, row: 0, label: 'Gate 4 — результаты пилота' },
      { id: 'g4back', type: 'end', lane: 'pilot', col: 11, row: 1, label: 'Kill / Redirect: доработка прототипа' },
      { id: 'g5', type: 'xor', lane: 'dtszn', col: 12, row: 0, label: 'Gate 5 — решение о масштабировании' },
      { id: 'scale', type: 'user', lane: 'dtszn', col: 13, row: 0, label: 'Тиражировать: обучение и методические материалы' },
      { id: 'fin', type: 'end', lane: 'dtszn', col: 14, row: 0, label: 'Улучшение внедрено в учреждениях' },
      { id: 'g5keep', type: 'end', lane: 'dtszn', col: 12, row: 1, label: 'Сохранить как практику без тиражирования' },
    ],
    flows: [
      { from: 'st', to: 'form' }, { from: 'form', to: 'g1in', kind: 'message' },
      { from: 'g1in', to: 'g1eval' }, { from: 'g1eval', to: 'g1' },
      { from: 'g1', to: 'g2eval', label: 'Go' }, { from: 'g1', to: 'g1kill', label: 'Kill / Hold' },
      { from: 'g2eval', to: 'g2' },
      { from: 'g2', to: 'build', label: 'Go' }, { from: 'g2', to: 'g2back', label: 'Kill / Redirect' },
      { from: 'build', to: 'g3' },
      { from: 'g3', to: 'run', label: 'Go' },
      { from: 'run', to: 'fb' }, { from: 'fb', to: 'g4' },
      { from: 'g4', to: 'g5', label: 'Go' }, { from: 'g4', to: 'g4back', label: 'Kill / Redirect' },
      { from: 'g5', to: 'scale', label: 'Go' }, { from: 'g5', to: 'g5keep', label: 'Kill' },
      { from: 'scale', to: 'fin' },
    ],
    walkthrough: [
      { node: 'st', title: 'Триггер процесса', body: 'Всё начинается не с распоряжения сверху, а с проблемы, которую сотрудник видит в своей работе: избыточная операция, потеря времени, неудобство для гражданина.' },
      { node: 'form', title: 'Формулировка инициативы', body: 'Сотрудник описывает проблему, предлагаемое решение и ожидаемый эффект. Этап 1 не содержит точки принятия решения — инициатива уходит дальше автоматически.' },
      { node: 'g1', title: 'Gate 1 — первый фильтр', body: 'Руководитель учреждения оценивает соответствие регламентам и потенциал локального улучшения. Срок — 3 рабочих дня; платформа отслеживает его и эскалирует просрочку.' },
      { node: 'g2', title: 'Gate 2 — стратегическая оценка', body: 'Эксперты ДТСЗН смотрят шире: совместимость с целями Департамента, потенциал масштабирования, ожидаемый эффект, техническую осуществимость. Срок — 5 рабочих дней.' },
      { node: 'build', title: 'Разработка прототипа', body: 'Команда цифровой трансформации создаёт минимально жизнеспособный продукт по Agile. Приоритеты каждого спринта утверждает продакт-менеджер ДТСЗН.' },
      { node: 'run', title: 'Проверка в реальной работе', body: 'Пилотное учреждение внедряет прототип на месяц. Собираются данные об эффективности, удобстве и влиянии на процессы — от сотрудников и от граждан.' },
      { node: 'g4', title: 'Gate 4 — доказательство эффекта', body: 'Ключевая точка: заявленный эффект должен подтвердиться фактическими данными пилота. Здесь отсеиваются решения, которые выглядели хорошо на бумаге.' },
      { node: 'g5', title: 'Gate 5 — решение о тиражировании', body: 'ДТСЗН оценивает подтверждённый эффект, готовность других учреждений и наличие ресурсов. Масштабирование должно начаться в течение 2 недель после решения.' },
      { node: 'fin', title: 'Конечный продукт экосистемы', body: 'Не база предложений, а поток реально внедрённых улучшений. Именно этот показатель платформа считает главным.' },
    ],
  },

  // ══════════════════════════════ СОТРУДНИК ══════════════════
  {
    id: 'emp-submit', role: 'employee', group: 'Сотрудник учреждения',
    title: 'Подача инициативы',
    description: 'Путь от обнаруженной проблемы до задачи в кабинете руководителя. Платформа помогает не дублировать чужие усилия и сама маршрутизирует инициативу.',
    lanes: [L.emp, L.sys],
    nodes: [
      { id: 'st', type: 'start', lane: 'emp', col: 0, row: 0, label: 'Обнаружена проблема в процессе или услуге' },
      { id: 'search', type: 'user', lane: 'emp', col: 1, row: 0, label: 'Проверить похожие идеи на доске' },
      { id: 'gdup', type: 'xor', lane: 'emp', col: 2, row: 0, label: 'Похожая идея уже есть?' },
      { id: 'support', type: 'user', lane: 'emp', col: 3, row: 1, label: 'Поддержать голосом и дополнить комментарием' },
      { id: 'endsup', type: 'end', lane: 'emp', col: 4, row: 1, label: 'Усилия объединены, дублирование исключено' },
      { id: 'fill', type: 'user', lane: 'emp', col: 3, row: 0, label: 'Заполнить форму: проблема, решение, эффект' },
      { id: 'ai', type: 'service', lane: 'sys', col: 4, row: 0, label: 'Определить направление и найти похожие инициативы' },
      { id: 'check', type: 'user', lane: 'emp', col: 5, row: 0, label: 'Уточнить описание и измерить эффект числом' },
      { id: 'send', type: 'user', lane: 'emp', col: 6, row: 0, label: 'Отправить инициативу' },
      { id: 'num', type: 'service', lane: 'sys', col: 7, row: 0, label: 'Присвоить номер, создать задачу руководителю' },
      { id: 'wait', type: 'timer', lane: 'emp', col: 8, row: 0, label: 'Ожидание решения Gate 1 — 3 рабочих дня' },
      { id: 'end', type: 'end', lane: 'emp', col: 9, row: 0, label: 'Получено решение с обоснованием' },
    ],
    flows: [
      { from: 'st', to: 'search' }, { from: 'search', to: 'gdup' },
      { from: 'gdup', to: 'support', label: 'да' }, { from: 'support', to: 'endsup' },
      { from: 'gdup', to: 'fill', label: 'нет' },
      { from: 'fill', to: 'ai', kind: 'message' }, { from: 'ai', to: 'check', kind: 'message' },
      { from: 'check', to: 'send' }, { from: 'send', to: 'num', kind: 'message' },
      { from: 'num', to: 'wait', kind: 'message' }, { from: 'wait', to: 'end' },
    ],
    walkthrough: [
      { node: 'search', title: 'Сначала посмотрите доску идей', body: 'Часто проблему уже сформулировал коллега из другого учреждения. Присоединиться к существующей инициативе быстрее, чем вести свою с нуля.' },
      { node: 'gdup', title: 'Развилка: поддержать или подать своё', body: 'Если совпадение высокое — поддержите голосом и добавьте свой контекст в комментарии. Решение сразу будет проектироваться под несколько типов учреждений.' },
      { node: 'fill', title: 'Четыре вопроса обычным языком', body: 'Какую проблему обнаружили, что предлагаете, какой эффект это даст и чем он измеряется. Технических навыков форма не требует.' },
      { node: 'ai', title: 'ИИ-подсказчик работает по ходу', body: 'Пока вы пишете, система определяет тематическое направление и показывает похожие инициативы с процентом совпадения. Классификация носит рекомендательный характер.' },
      { node: 'check', title: 'Цифра усиливает инициативу', body: 'Даже приблизительная оценка эффекта позволит на пилоте сравнить прогноз с фактом. Это поле эксперты читают внимательнее всего.' },
      { node: 'num', title: 'Дальше платформа действует сама', body: 'Инициатива получает номер вида SOC-2026-0001 и уходит руководителю вашего учреждения: этап 1 не содержит точки принятия решения.' },
      { node: 'wait', title: 'Срок отслеживается системой', body: 'Три рабочих дня считаются с пропуском выходных. Если решение не принято вовремя, задача эскалируется координатору экосистемы.' },
    ],
  },
  {
    id: 'emp-pilot', role: 'employee', group: 'Сотрудник учреждения',
    title: 'Участие в пилоте и обратная связь',
    description: 'Сотрудники пилотного учреждения применяют прототип в реальной работе. Их отклики — основное доказательство на Gate 4.',
    lanes: [L.emp, L.sys, L.pilot],
    nodes: [
      { id: 'st', type: 'message', lane: 'emp', col: 0, row: 0, label: 'Учреждение выбрано пилотной площадкой' },
      { id: 'learn', type: 'user', lane: 'emp', col: 1, row: 0, label: 'Пройти обучение работе с прототипом' },
      { id: 'use', type: 'user', lane: 'emp', col: 2, row: 0, label: 'Применять решение в ежедневной работе' },
      { id: 'issue', type: 'xor', lane: 'emp', col: 3, row: 0, label: 'Возникла проблема?' },
      { id: 'report', type: 'user', lane: 'emp', col: 4, row: 1, label: 'Сообщить в обсуждении инициативы' },
      { id: 'timer', type: 'timer', lane: 'emp', col: 4, row: 0, label: 'Пилотный период — 1 месяц' },
      { id: 'survey', type: 'user', lane: 'emp', col: 5, row: 0, label: 'Заполнить опрос по итогам пилота' },
      { id: 'nlp', type: 'service', lane: 'sys', col: 6, row: 0, label: 'Разобрать отклики: тональность, темы, сигналы' },
      { id: 'analyse', type: 'user', lane: 'pilot', col: 7, row: 0, label: 'Сопоставить отклики с фактическими KPI' },
      { id: 'end', type: 'end', lane: 'pilot', col: 8, row: 0, label: 'Доказательная база для Gate 4 готова' },
    ],
    flows: [
      { from: 'st', to: 'learn' }, { from: 'learn', to: 'use' }, { from: 'use', to: 'issue' },
      { from: 'issue', to: 'report', label: 'да' }, { from: 'report', to: 'use' },
      { from: 'issue', to: 'timer', label: 'нет' },
      { from: 'timer', to: 'survey' }, { from: 'survey', to: 'nlp', kind: 'message' },
      { from: 'nlp', to: 'analyse', kind: 'message' }, { from: 'analyse', to: 'end' },
    ],
    walkthrough: [
      { node: 'learn', title: 'Обучение — до старта пилота', body: 'Опыт завершённых пилотов показал: если учить в первый день, вся первая неделя уходит на освоение и портит статистику.' },
      { node: 'issue', title: 'Проблемы фиксируются сразу', body: 'Не копите замечания до финального опроса. Сообщение в обсуждении инициативы попадает напрямую команде разработки.' },
      { node: 'survey', title: 'Опрос — не формальность', body: 'Шкала удобства, влияние на рабочее время и свободный отзыв. Именно эти данные защищают инициативу на Gate 4.' },
      { node: 'nlp', title: 'Тексты разбираются автоматически', body: 'Свободные ответы проходят разбор: тональность, повторяющиеся темы, отдельно выделенные проблемные сигналы с цитатами.' },
      { node: 'end', title: 'Что решает судьбу инициативы', body: 'Доказанность эффекта, удовлетворённость пользователей, отсутствие критических проблем и соблюдение требований к защите данных.' },
    ],
  },

  // ══════════════════════════════ РУКОВОДИТЕЛЬ ═══════════════
  {
    id: 'head-gate1', role: 'head', group: 'Руководитель учреждения',
    title: 'Решение на Gate 1',
    description: 'Первый уровень контроля. Руководитель — владелец процессов и заказчик изменений в своём учреждении.',
    sla: '3 рабочих дня',
    lanes: [L.sys, L.head, L.emp],
    nodes: [
      { id: 'task', type: 'message', lane: 'sys', col: 0, row: 0, label: 'Задача на Gate 1 в кабинете руководителя' },
      { id: 'read', type: 'user', lane: 'head', col: 1, row: 0, label: 'Изучить проблему и предлагаемое решение' },
      { id: 'votes', type: 'user', lane: 'head', col: 2, row: 0, label: 'Посмотреть поддержку коллег и похожие инициативы' },
      { id: 'crit', type: 'user', lane: 'head', col: 3, row: 0, label: 'Оценить по трём критериям Gate 1' },
      { id: 'gw', type: 'xor', lane: 'head', col: 4, row: 0, label: 'Решение с обязательной аргументацией' },
      { id: 'go', type: 'service', lane: 'sys', col: 5, row: 0, label: 'Передать на экспертизу ДТСЗН' },
      { id: 'hold', type: 'user', lane: 'head', col: 5, row: 1, label: 'Запросить недостающие сведения у автора' },
      { id: 'redir', type: 'user', lane: 'head', col: 5, row: 2, label: 'Вернуть автору на доработку' },
      { id: 'kill', type: 'end', lane: 'head', col: 5, row: 3, label: 'Остановлено: обоснование в архиве знаний' },
      { id: 'endgo', type: 'end', lane: 'sys', col: 6, row: 0, label: 'Инициатива на этапе экспертизы' },
      { id: 'notify', type: 'message', lane: 'emp', col: 6, row: 1, label: 'Автор уведомлён и дополняет инициативу' },
      { id: 'sla', type: 'timer', lane: 'head', col: 3, row: 1, label: 'Истекли 3 рабочих дня' },
      { id: 'esc', type: 'end', lane: 'head', col: 4, row: 1, label: 'Эскалация координатору экосистемы' },
    ],
    flows: [
      { from: 'task', to: 'read', kind: 'message' }, { from: 'read', to: 'votes' },
      { from: 'votes', to: 'crit' }, { from: 'crit', to: 'gw' },
      { from: 'gw', to: 'go', label: 'Go' }, { from: 'go', to: 'endgo' },
      { from: 'gw', to: 'hold', label: 'Hold' }, { from: 'hold', to: 'notify', kind: 'message' },
      { from: 'gw', to: 'redir', label: 'Redirect' }, { from: 'redir', to: 'notify', kind: 'message' },
      { from: 'gw', to: 'kill', label: 'Kill' },
      { from: 'read', to: 'sla', label: 'решение не принято' }, { from: 'sla', to: 'esc' },
    ],
    walkthrough: [
      { node: 'task', title: 'Задачу создаёт движок процесса', body: 'Инициатива адресуется строго руководителю учреждения автора. Решить за чужое учреждение платформа не позволит.' },
      { node: 'votes', title: 'Поддержка коллег как контекст', body: 'Число голосов показывает, насколько проблема распространена. Это сигнал приоритета, но не замена вашей оценке.' },
      { node: 'crit', title: 'Критерии заданы заранее', body: 'Соответствие внутренним политикам, потенциал локального улучшения, реалистичность в рамках бюджета. Перечень настраивается администратором.' },
      { node: 'gw', title: 'Четыре решения, и все документируются', body: 'Go — продолжить. Kill — остановить: это не провал, а экономия ресурсов. Hold — приостановить до получения данных. Redirect — вернуть на доработку. Без аргументации система решение не примет.' },
      { node: 'kill', title: 'Отказ тоже приносит пользу', body: 'Обоснование попадает в архив знаний и уходит автору. Неудачная, но продуманная инициатива — часть учебного процесса, а не повод для санкций.' },
      { node: 'sla', title: 'Срок под контролем системы', body: 'Три рабочих дня считаются с пропуском выходных. Просроченная задача переходит в статус эскалации, координатор экосистемы получает уведомление.' },
    ],
  },
  {
    id: 'head-pilot', role: 'head', group: 'Руководитель учреждения',
    title: 'Заявка учреждения на роль пилотной площадки',
    description: 'Учреждение само предлагает себя площадкой для проверки прототипа в реальных условиях.',
    lanes: [L.head, L.pilot, L.emp],
    nodes: [
      { id: 'st', type: 'start', lane: 'head', col: 0, row: 0, label: 'На доске идей замечен подходящий прототип' },
      { id: 'assess', type: 'user', lane: 'head', col: 1, row: 0, label: 'Оценить готовность учреждения и ресурсы' },
      { id: 'apply', type: 'user', lane: 'head', col: 2, row: 0, label: 'Подать заявку с обоснованием' },
      { id: 'review', type: 'user', lane: 'pilot', col: 3, row: 0, label: 'Рассмотреть заявку площадки' },
      { id: 'gw', type: 'xor', lane: 'pilot', col: 4, row: 0, label: 'Площадка подходит?' },
      { id: 'no', type: 'end', lane: 'pilot', col: 5, row: 1, label: 'Отказ с пояснением' },
      { id: 'plan', type: 'user', lane: 'pilot', col: 5, row: 0, label: 'Запланировать пилот: сроки, KPI, участники' },
      { id: 'prep', type: 'user', lane: 'head', col: 6, row: 0, label: 'Выделить сотрудников и обеспечить условия' },
      { id: 'base', type: 'user', lane: 'head', col: 7, row: 0, label: 'Снять базовые значения показателей до старта' },
      { id: 'start', type: 'message', lane: 'emp', col: 8, row: 0, label: 'Сотрудники приступают к пилоту' },
    ],
    flows: [
      { from: 'st', to: 'assess' }, { from: 'assess', to: 'apply' },
      { from: 'apply', to: 'review', kind: 'message' }, { from: 'review', to: 'gw' },
      { from: 'gw', to: 'plan', label: 'да' }, { from: 'gw', to: 'no', label: 'нет' },
      { from: 'plan', to: 'prep', kind: 'message' }, { from: 'prep', to: 'base' },
      { from: 'base', to: 'start', kind: 'message' },
    ],
    walkthrough: [
      { node: 'assess', title: 'Готовность важнее энтузиазма', body: 'Нужны сотрудники, готовые работать по-новому месяц, и ответственный за сбор обратной связи. Без этого анкеты остаются незаполненными.' },
      { node: 'plan', title: 'KPI определяются до старта', body: 'Показатели берутся из заявленного эффекта инициативы: что именно должно измениться и на сколько.' },
      { node: 'base', title: 'Базовые замеры — обязательный шаг', body: 'Без значения «до» доказать эффект на Gate 4 невозможно. Снимайте показатели за одну-две недели до начала пилота.' },
    ],
  },
  {
    id: 'head-adopt', role: 'head', group: 'Руководитель учреждения',
    title: 'Внедрение практики из библиотеки',
    description: 'Масштабирование «снизу»: учреждение берёт проверенное решение по собственной инициативе, без директивы сверху.',
    lanes: [L.head, L.sys, L.dtszn],
    nodes: [
      { id: 'st', type: 'start', lane: 'head', col: 0, row: 0, label: 'Поиск решения похожей проблемы' },
      { id: 'lib', type: 'user', lane: 'head', col: 1, row: 0, label: 'Изучить библиотеку лучших практик' },
      { id: 'eff', type: 'user', lane: 'head', col: 2, row: 0, label: 'Проверить подтверждённый эффект и материалы' },
      { id: 'gw', type: 'xor', lane: 'head', col: 3, row: 0, label: 'Практика применима у нас?' },
      { id: 'no', type: 'end', lane: 'head', col: 4, row: 1, label: 'Продолжить поиск или подать свою инициативу' },
      { id: 'take', type: 'user', lane: 'head', col: 4, row: 0, label: 'Взять практику в работу' },
      { id: 'mark', type: 'service', lane: 'sys', col: 5, row: 0, label: 'Отметить внедрение как инициативное' },
      { id: 'train', type: 'user', lane: 'head', col: 6, row: 0, label: 'Обучить сотрудников по готовым материалам' },
      { id: 'done', type: 'user', lane: 'head', col: 7, row: 0, label: 'Подтвердить внедрение' },
      { id: 'metric', type: 'service', lane: 'dtszn', col: 8, row: 0, label: 'Учесть в показателе масштабирования «снизу»' },
      { id: 'end', type: 'end', lane: 'dtszn', col: 9, row: 0, label: 'Практика распространяется без директив' },
    ],
    flows: [
      { from: 'st', to: 'lib' }, { from: 'lib', to: 'eff' }, { from: 'eff', to: 'gw' },
      { from: 'gw', to: 'take', label: 'да' }, { from: 'gw', to: 'no', label: 'нет' },
      { from: 'take', to: 'mark', kind: 'message' }, { from: 'mark', to: 'train', kind: 'message' },
      { from: 'train', to: 'done' }, { from: 'done', to: 'metric', kind: 'message' }, { from: 'metric', to: 'end' },
    ],
    walkthrough: [
      { node: 'lib', title: 'Внутренний рынок решений', body: 'В библиотеке только практики, доказавшие эффект на пилоте: с методическими материалами, программой обучения и типовыми документами.' },
      { node: 'mark', title: 'Почему это важно измерять', body: 'Внедрение по инициативе учреждения помечается отдельно. Доля таких внедрений — показатель зрелости экосистемы и силы внутренней сети знаний.' },
      { node: 'end', title: 'Изменения поднимаются снизу', body: 'Цель платформы — чтобы улучшения не только спускались сверху, но и системно распространялись между учреждениями по их собственной инициативе.' },
    ],
  },

  // ══════════════════════════════ ЭКСПЕРТ ════════════════════
  {
    id: 'expert-gate2', role: 'expert', group: 'Эксперт ДТСЗН',
    title: 'Экспертиза на Gate 2',
    description: 'Стратегическая оценка: соответствие целям Департамента, потенциал масштабирования, осуществимость.',
    sla: '5 рабочих дней',
    lanes: [L.sys, L.expert, L.dev],
    nodes: [
      { id: 'in', type: 'message', lane: 'sys', col: 0, row: 0, label: 'Инициатива прошла Gate 1' },
      { id: 'ctx', type: 'user', lane: 'expert', col: 1, row: 0, label: 'Изучить инициативу и решение руководителя' },
      { id: 'sim', type: 'service', lane: 'sys', col: 2, row: 0, label: 'Показать похожие инициативы и прогноз успеха' },
      { id: 'dup', type: 'xor', lane: 'expert', col: 3, row: 0, label: 'Дублирует существующую работу?' },
      { id: 'merge', type: 'user', lane: 'expert', col: 4, row: 1, label: 'Объединить с существующей инициативой' },
      { id: 'endm', type: 'end', lane: 'expert', col: 5, row: 1, label: 'Redirect: усилия объединены' },
      { id: 'crit', type: 'user', lane: 'expert', col: 4, row: 0, label: 'Оценить по четырём критериям Gate 2' },
      { id: 'feas', type: 'user', lane: 'dev', col: 5, row: 0, label: 'Подтвердить техническую осуществимость' },
      { id: 'gw', type: 'xor', lane: 'expert', col: 6, row: 0, label: 'Вердикт комитета экспертов' },
      { id: 'go', type: 'user', lane: 'expert', col: 7, row: 0, label: 'Сформировать KPI и передать в разработку' },
      { id: 'endgo', type: 'end', lane: 'dev', col: 8, row: 0, label: 'Проект разработки создан' },
      { id: 'kill', type: 'end', lane: 'expert', col: 7, row: 1, label: 'Kill: нежизнеспособные проекты отсеяны' },
      { id: 'hold', type: 'end', lane: 'expert', col: 7, row: 2, label: 'Hold: ожидание данных или ресурсов' },
    ],
    flows: [
      { from: 'in', to: 'ctx', kind: 'message' }, { from: 'ctx', to: 'sim', kind: 'message' },
      { from: 'sim', to: 'dup', kind: 'message' },
      { from: 'dup', to: 'merge', label: 'да' }, { from: 'merge', to: 'endm' },
      { from: 'dup', to: 'crit', label: 'нет' },
      { from: 'crit', to: 'feas', kind: 'message' }, { from: 'feas', to: 'gw', kind: 'message' },
      { from: 'gw', to: 'go', label: 'Go' }, { from: 'go', to: 'endgo', kind: 'message' },
      { from: 'gw', to: 'kill', label: 'Kill' }, { from: 'gw', to: 'hold', label: 'Hold' },
    ],
    walkthrough: [
      { node: 'sim', title: 'ИИ подсказывает, но не решает', body: 'Система показывает похожие инициативы с процентом совпадения и прогноз успеха с раскрытием факторов. Вердикт остаётся за экспертом.' },
      { node: 'dup', title: 'Дублирование — частая причина Redirect', body: 'Если проблема одна, а контекст разный, инициативы объединяются: решение сразу проектируется под несколько типов учреждений.' },
      { node: 'crit', title: 'Четыре критерия Gate 2', body: 'Стратегическая совместимость с целями Департамента, потенциал масштабирования, ожидаемый эффект, техническая осуществимость на уровне идеи.' },
      { node: 'go', title: 'KPI задаются здесь', body: 'Показатели, определённые на экспертизе, станут критериями оценки пилота на Gate 4. Их нельзя откладывать «на потом».' },
      { node: 'kill', title: 'Kill — признак здоровой системы', body: 'Решения об остановке не считаются негативным показателем: они экономят ресурсы и не дают нежизнеспособным проектам дойти до разработки.' },
    ],
  },
  {
    id: 'expert-practice', role: 'expert', group: 'Эксперт ДТСЗН',
    title: 'Публикация лучшей практики',
    description: 'Превращение доказавшего эффект решения в тиражируемую практику с материалами для внедрения.',
    lanes: [L.expert, L.pilot, L.head],
    nodes: [
      { id: 'st', type: 'message', lane: 'expert', col: 0, row: 0, label: 'Инициатива прошла Gate 4 или Gate 5' },
      { id: 'data', type: 'user', lane: 'pilot', col: 1, row: 0, label: 'Передать данные пилота и отклики участников' },
      { id: 'sum', type: 'user', lane: 'expert', col: 2, row: 0, label: 'Сформулировать суть решения без жаргона' },
      { id: 'eff', type: 'user', lane: 'expert', col: 3, row: 0, label: 'Описать подтверждённый эффект с цифрами' },
      { id: 'mat', type: 'user', lane: 'expert', col: 4, row: 0, label: 'Подготовить материалы: инструкции, обучение, типовые документы' },
      { id: 'pub', type: 'user', lane: 'expert', col: 5, row: 0, label: 'Опубликовать в библиотеке практик' },
      { id: 'award', type: 'service', lane: 'expert', col: 6, row: 0, label: 'Отметить автора инициативы признанием' },
      { id: 'take', type: 'user', lane: 'head', col: 7, row: 0, label: 'Учреждения берут практику в работу' },
      { id: 'end', type: 'end', lane: 'head', col: 8, row: 0, label: 'Решение распространяется по сети учреждений' },
    ],
    flows: [
      { from: 'st', to: 'data', kind: 'message' }, { from: 'data', to: 'sum', kind: 'message' },
      { from: 'sum', to: 'eff' }, { from: 'eff', to: 'mat' }, { from: 'mat', to: 'pub' },
      { from: 'pub', to: 'award' }, { from: 'award', to: 'take', kind: 'message' }, { from: 'take', to: 'end' },
    ],
    walkthrough: [
      { node: 'sum', title: 'Пишите для того, кто не участвовал', body: 'Читатель практики — руководитель другого учреждения. Ему нужно понять суть за минуту и решить, применимо ли это у него.' },
      { node: 'eff', title: 'Цифры пилота, а не прогноз', body: 'Указывается фактический результат: «экономия 47 минут в день при прогнозе 45». Именно расхождение прогноза и факта вызывает доверие.' },
      { node: 'mat', title: 'Без материалов практику не повторят', body: 'Методические рекомендации, инструкция пользователя, программа обучения и типовой приказ — иначе внедрение упрётся в организационные вопросы.' },
      { node: 'award', title: 'Публичное признание автора', body: 'Нематериальное стимулирование — часть управленческого аппарата экосистемы наравне с материальным.' },
    ],
  },

  // ══════════════════════════════ РАЗРАБОТКА ═════════════════
  {
    id: 'dev-build', role: 'developer', group: 'Команда разработки и ЦТ',
    title: 'Разработка прототипа и Gate 3',
    description: 'Итеративное создание MVP по Agile с постоянной обратной связью от будущих пользователей.',
    sla: '4 спринта по 2 недели',
    lanes: [L.dev, L.dtszn, L.emp, L.supplier],
    nodes: [
      { id: 'st', type: 'message', lane: 'dev', col: 0, row: 0, label: 'Положительное решение Gate 2' },
      { id: 'proj', type: 'user', lane: 'dev', col: 1, row: 0, label: 'Создать проект и наполнить бэклог' },
      { id: 'po', type: 'user', lane: 'dtszn', col: 2, row: 0, label: 'Утвердить приоритеты спринта' },
      { id: 'sprint', type: 'user', lane: 'dev', col: 3, row: 0, label: 'Выполнить спринт — 2 недели' },
      { id: 'need', type: 'xor', lane: 'dev', col: 2, row: 1, label: 'Нужна внешняя компетенция?' },
      { id: 'vendor', type: 'user', lane: 'supplier', col: 3, row: 1, label: 'Предоставить компоненты и компетенции' },
      { id: 'demo', type: 'user', lane: 'dev', col: 4, row: 0, label: 'Демонстрация ключевым пользователям' },
      { id: 'fb', type: 'user', lane: 'emp', col: 5, row: 0, label: 'Дать обратную связь по прототипу' },
      { id: 'gw', type: 'xor', lane: 'dev', col: 6, row: 0, label: 'MVP готов к пилоту?' },
      { id: 'g3', type: 'xor', lane: 'dev', col: 7, row: 0, label: 'Gate 3 — решение продакт-менеджера' },
      { id: 'doc', type: 'user', lane: 'dev', col: 8, row: 0, label: 'Подготовить документацию и инструкции' },
      { id: 'end', type: 'end', lane: 'dev', col: 9, row: 0, label: 'Прототип передан на пилотирование' },
      { id: 'redir', type: 'end', lane: 'dev', col: 8, row: 1, label: 'Redirect: изменить функциональность' },
      { id: 'kill', type: 'end', lane: 'dev', col: 8, row: 2, label: 'Kill: остановить разработку' },
    ],
    flows: [
      { from: 'st', to: 'proj' }, { from: 'proj', to: 'po', kind: 'message' },
      { from: 'po', to: 'sprint', kind: 'message' },
      { from: 'proj', to: 'need' }, { from: 'need', to: 'vendor', label: 'да', kind: 'message' },
      { from: 'vendor', to: 'sprint', kind: 'message' },
      { from: 'sprint', to: 'demo' }, { from: 'demo', to: 'fb', kind: 'message' },
      { from: 'fb', to: 'gw', kind: 'message' },
      { from: 'gw', to: 'po', label: 'нет — следующий спринт' },
      { from: 'gw', to: 'g3', label: 'да' },
      { from: 'g3', to: 'doc', label: 'Go' }, { from: 'doc', to: 'end' },
      { from: 'g3', to: 'redir', label: 'Redirect' }, { from: 'g3', to: 'kill', label: 'Kill' },
    ],
    walkthrough: [
      { node: 'po', title: 'Заказчик участвует в каждом спринте', body: 'Представитель ДТСЗН в роли продакт-менеджера утверждает приоритеты. Это условие Agile-контракта: состав MVP определяется совместно, а не постфактум.' },
      { node: 'sprint', title: 'Четыре спринта по две недели', body: 'План разработки фиксируется при передаче инициативы. Доска задач, спринты и бэклог продукта ведутся прямо в платформе.' },
      { node: 'vendor', title: 'Поставщики подключаются точечно', body: 'Готовые компоненты, программные продукты и консалтинг — там, где разрабатывать с нуля дороже, чем взять существующее.' },
      { node: 'fb', title: 'Обратная связь до пилота, а не после', body: 'Промежуточные демонстрации будущим пользователям снимают риск обнаружить неудобство уже на пилоте, когда переделывать дорого.' },
      { node: 'g3', title: 'Критерии Gate 3', body: 'Достигнутые цели спринтов, наличие рабочего MVP, положительная обратная связь на демонстрациях. Решение принимает продакт-менеджер.' },
    ],
  },

  // ══════════════════════════════ ПОСТАВЩИК ══════════════════
  {
    id: 'supplier', role: 'supplier', group: 'Поставщик технологий и услуг',
    title: 'Участие поставщика в проекте',
    description: 'Предоставление готовых компонентов, технологий и компетенций для создания и пилотирования прототипа.',
    lanes: [L.dev, L.supplier, L.dtszn],
    nodes: [
      { id: 'st', type: 'message', lane: 'dev', col: 0, row: 0, label: 'В проекте нужна внешняя компетенция' },
      { id: 'req', type: 'user', lane: 'dev', col: 1, row: 0, label: 'Сформулировать требование к компоненту' },
      { id: 'see', type: 'user', lane: 'supplier', col: 2, row: 0, label: 'Изучить инициативу на этапе разработки' },
      { id: 'gw', type: 'xor', lane: 'supplier', col: 3, row: 0, label: 'Есть подходящее решение?' },
      { id: 'no', type: 'end', lane: 'supplier', col: 4, row: 1, label: 'Отказ — команда ищет другой вариант' },
      { id: 'offer', type: 'user', lane: 'supplier', col: 4, row: 0, label: 'Предложить компонент или услугу' },
      { id: 'appr', type: 'user', lane: 'dtszn', col: 5, row: 0, label: 'Согласовать условия и ресурсы' },
      { id: 'deliver', type: 'user', lane: 'supplier', col: 6, row: 0, label: 'Передать компонент и сопровождать интеграцию' },
      { id: 'test', type: 'user', lane: 'dev', col: 7, row: 0, label: 'Встроить и проверить в составе прототипа' },
      { id: 'end', type: 'end', lane: 'dev', col: 8, row: 0, label: 'Компонент работает в составе решения' },
    ],
    flows: [
      { from: 'st', to: 'req' }, { from: 'req', to: 'see', kind: 'message' }, { from: 'see', to: 'gw' },
      { from: 'gw', to: 'offer', label: 'да' }, { from: 'gw', to: 'no', label: 'нет' },
      { from: 'offer', to: 'appr', kind: 'message' }, { from: 'appr', to: 'deliver', kind: 'message' },
      { from: 'deliver', to: 'test', kind: 'message' }, { from: 'test', to: 'end' },
    ],
    walkthrough: [
      { node: 'see', title: 'Видимость ограничена этапом', body: 'Поставщику доступны инициативы, дошедшие до разработки и пилотирования. Ранние идеи сотрудников остаются внутри Департамента.' },
      { node: 'appr', title: 'Условия согласует заказчик', body: 'Ресурсы и условия подтверждает центральный аппарат ДТСЗН — это исключает договорённости в обход владельца бюджета.' },
      { node: 'deliver', title: 'Не только передача, но и сопровождение', body: 'Поставщик отвечает за интеграцию компонента в прототип, а не только за его поставку.' },
    ],
  },

  // ══════════════════════════════ ПИЛОТЫ ═════════════════════
  {
    id: 'pilot-run', role: 'pilot_coordinator', group: 'Координатор пилотных площадок',
    title: 'Организация пилота и Gate 4',
    description: 'Проверка прототипа в реальных условиях со сбором доказательной базы: KPI, отклики сотрудников и граждан.',
    sla: '1 месяц пилота + 1 неделя анализа',
    lanes: [L.dev, L.pilot, L.head, L.emp],
    nodes: [
      { id: 'st', type: 'message', lane: 'dev', col: 0, row: 0, label: 'Прототип прошёл Gate 3' },
      { id: 'apps', type: 'user', lane: 'pilot', col: 1, row: 0, label: 'Рассмотреть заявки учреждений на площадку' },
      { id: 'pick', type: 'user', lane: 'pilot', col: 2, row: 0, label: 'Выбрать площадку и утвердить план' },
      { id: 'kpi', type: 'user', lane: 'pilot', col: 3, row: 0, label: 'Задать KPI: база, цель, направление улучшения' },
      { id: 'train', type: 'user', lane: 'head', col: 4, row: 0, label: 'Обучить сотрудников до старта' },
      { id: 'run', type: 'user', lane: 'emp', col: 5, row: 0, label: 'Применять решение в работе — 1 месяц' },
      { id: 'watch', type: 'service', lane: 'pilot', col: 6, row: 0, label: 'Еженедельно снимать показатели' },
      { id: 'crit', type: 'xor', lane: 'pilot', col: 6, row: 1, label: 'Критический сбой?' },
      { id: 'stop', type: 'end', lane: 'pilot', col: 7, row: 1, label: 'Досрочная остановка пилота' },
      { id: 'survey', type: 'user', lane: 'emp', col: 7, row: 0, label: 'Заполнить опрос по итогам' },
      { id: 'nlp', type: 'service', lane: 'pilot', col: 8, row: 0, label: 'Разобрать отклики и сопоставить с KPI' },
      { id: 'gw', type: 'xor', lane: 'pilot', col: 9, row: 0, label: 'Gate 4 — эффект доказан?' },
      { id: 'go', type: 'end', lane: 'pilot', col: 10, row: 0, label: 'Go: передано на решение о масштабировании' },
      { id: 'redir', type: 'end', lane: 'pilot', col: 10, row: 1, label: 'Redirect: доработка и повторный пилот' },
      { id: 'kill', type: 'end', lane: 'pilot', col: 10, row: 2, label: 'Kill: эффект не подтвердился' },
    ],
    flows: [
      { from: 'st', to: 'apps', kind: 'message' }, { from: 'apps', to: 'pick' }, { from: 'pick', to: 'kpi' },
      { from: 'kpi', to: 'train', kind: 'message' }, { from: 'train', to: 'run', kind: 'message' },
      { from: 'run', to: 'watch', kind: 'message' }, { from: 'watch', to: 'crit' },
      { from: 'crit', to: 'stop', label: 'да' },
      { from: 'watch', to: 'survey', kind: 'message' },
      { from: 'survey', to: 'nlp', kind: 'message' }, { from: 'nlp', to: 'gw' },
      { from: 'gw', to: 'go', label: 'Go' }, { from: 'gw', to: 'redir', label: 'Redirect' },
      { from: 'gw', to: 'kill', label: 'Kill' },
    ],
    walkthrough: [
      { node: 'apps', title: 'Площадки вызываются, а не назначаются', body: 'Учреждения сами заявляют готовность. Мотивированная площадка даёт качественную обратную связь, назначенная — формальные отписки.' },
      { node: 'kpi', title: 'KPI приходят из заявленного эффекта', body: 'Показатели не выдумываются заново: берётся то, что автор обещал на этапе подачи, с базовым и целевым значением.' },
      { node: 'train', title: 'Обучение до старта, не в первый день', body: 'Иначе первая неделя уходит на освоение и искажает статистику всего пилота.' },
      { node: 'crit', title: 'Критерий остановки — заранее', body: 'Договоритесь до старта, что считается критическим сбоем. Иначе спор о продолжении возникнет в самый неподходящий момент.' },
      { node: 'gw', title: 'Четыре критерия Gate 4', body: 'Доказанность заявленного эффекта, удовлетворённость пользователей, отсутствие критических проблем, соответствие требованиям безопасности и конфиденциальности.' },
    ],
  },

  // ══════════════════════════════ ДТСЗН ══════════════════════
  {
    id: 'dtszn-scale', role: 'dtszn', group: 'ДТСЗН (центральный аппарат)',
    title: 'Решение о масштабировании и тиражирование',
    description: 'Превращение подтверждённого на пилоте решения в изменение по всей сети учреждений.',
    sla: 'начало в течение 2 недель',
    lanes: [L.pilot, L.dtszn, L.head, L.sys],
    nodes: [
      { id: 'st', type: 'message', lane: 'pilot', col: 0, row: 0, label: 'Пилот завершён с решением Go' },
      { id: 'rev', type: 'user', lane: 'dtszn', col: 1, row: 0, label: 'Проверить подтверждённый эффект и данные пилота' },
      { id: 'ready', type: 'user', lane: 'dtszn', col: 2, row: 0, label: 'Оценить готовность учреждений и ресурсы' },
      { id: 'gw', type: 'xor', lane: 'dtszn', col: 3, row: 0, label: 'Gate 5 — масштабировать?' },
      { id: 'keep', type: 'end', lane: 'dtszn', col: 4, row: 1, label: 'Kill: сохранить как практику без тиражирования' },
      { id: 'plan', type: 'user', lane: 'dtszn', col: 4, row: 0, label: 'Утвердить план тиражирования и ресурсы' },
      { id: 'timer', type: 'timer', lane: 'dtszn', col: 5, row: 0, label: 'Начать в течение 2 недель' },
      { id: 'mat', type: 'user', lane: 'dtszn', col: 6, row: 0, label: 'Подготовить методические материалы и обучение' },
      { id: 'roll', type: 'user', lane: 'head', col: 7, row: 0, label: 'Внедрить решение в учреждении' },
      { id: 'mon', type: 'service', lane: 'sys', col: 8, row: 0, label: 'Отслеживать ход внедрения по учреждениям' },
      { id: 'val', type: 'service', lane: 'sys', col: 9, row: 0, label: 'Пересчитать валоризацию эффекта' },
      { id: 'end', type: 'end', lane: 'dtszn', col: 10, row: 0, label: 'Улучшение работает в масштабе города' },
    ],
    flows: [
      { from: 'st', to: 'rev', kind: 'message' }, { from: 'rev', to: 'ready' }, { from: 'ready', to: 'gw' },
      { from: 'gw', to: 'plan', label: 'Go' }, { from: 'gw', to: 'keep', label: 'Kill' },
      { from: 'plan', to: 'timer' }, { from: 'timer', to: 'mat' },
      { from: 'mat', to: 'roll', kind: 'message' }, { from: 'roll', to: 'mon', kind: 'message' },
      { from: 'mon', to: 'val' }, { from: 'val', to: 'end', kind: 'message' },
    ],
    walkthrough: [
      { node: 'rev', title: 'Решение опирается на данные пилота', body: 'Не на убеждённость авторов и не на симпатию к идее: только фактические KPI и отклики участников.' },
      { node: 'gw', title: 'Kill здесь не отменяет ценность', body: 'Решение может быть полезным локально, но не требовать централизованного тиражирования. Тогда оно остаётся в библиотеке практик для добровольного внедрения.' },
      { node: 'timer', title: 'Срок начала тиражирования', body: 'Две недели после решения. Затягивание на этом этапе — самый заметный для сотрудников признак бюрократического застоя.' },
      { node: 'val', title: 'Эффект пересчитывается в масштабе', body: 'Экономия одного учреждения умножается на число внедривших. Так локальные 47 минут в день превращаются в 21 тысячу человеко-часов в год.' },
    ],
  },
  {
    id: 'dtszn-sla', role: 'dtszn', group: 'ДТСЗН (центральный аппарат)',
    title: 'Контроль SLA и эскалация',
    description: 'Противодействие главному риску экосистемы — бюрократическому застою, когда сроки игнорируются из-за загрузки персонала.',
    lanes: [L.sys, L.dtszn, L.head],
    nodes: [
      { id: 'st', type: 'timer', lane: 'sys', col: 0, row: 0, label: 'Фоновая проверка каждые 15 минут' },
      { id: 'scan', type: 'service', lane: 'sys', col: 1, row: 0, label: 'Сверить сроки всех активных инициатив' },
      { id: 'gw', type: 'xor', lane: 'sys', col: 2, row: 0, label: 'Срок нарушен?' },
      { id: 'ok', type: 'end', lane: 'sys', col: 3, row: 1, label: 'Все решения в рамках срока' },
      { id: 'esc', type: 'service', lane: 'sys', col: 3, row: 0, label: 'Перевести задачу в статус эскалации' },
      { id: 'notify', type: 'message', lane: 'dtszn', col: 4, row: 0, label: 'Уведомление координатору экосистемы' },
      { id: 'analyse', type: 'user', lane: 'dtszn', col: 5, row: 0, label: 'Разобрать причину задержки' },
      { id: 'cause', type: 'xor', lane: 'dtszn', col: 6, row: 0, label: 'Причина задержки' },
      { id: 'push', type: 'user', lane: 'head', col: 7, row: 0, label: 'Принять решение по инициативе' },
      { id: 'res', type: 'user', lane: 'dtszn', col: 7, row: 1, label: 'Выделить ресурсы или экспертизу' },
      { id: 'norm', type: 'user', lane: 'dtszn', col: 7, row: 2, label: 'Пересмотреть норматив срока в настройках' },
      { id: 'audit', type: 'service', lane: 'sys', col: 8, row: 0, label: 'Зафиксировать в журнале аудита' },
      { id: 'end', type: 'end', lane: 'sys', col: 9, row: 0, label: 'Задержка устранена, причина учтена' },
    ],
    flows: [
      { from: 'st', to: 'scan' }, { from: 'scan', to: 'gw' },
      { from: 'gw', to: 'esc', label: 'да' }, { from: 'gw', to: 'ok', label: 'нет' },
      { from: 'esc', to: 'notify', kind: 'message' }, { from: 'notify', to: 'analyse' },
      { from: 'analyse', to: 'cause' },
      { from: 'cause', to: 'push', label: 'загрузка' },
      { from: 'cause', to: 'res', label: 'нехватка ресурсов' },
      { from: 'cause', to: 'norm', label: 'норматив занижен' },
      { from: 'push', to: 'audit', kind: 'message' },
      { from: 'res', to: 'audit', kind: 'message' }, { from: 'norm', to: 'audit', kind: 'message' },
      { from: 'audit', to: 'end' },
    ],
    walkthrough: [
      { node: 'st', title: 'Контроль не требует участия человека', body: 'Проверка запускается сама. Это принципиально: контроль, зависящий от того, вспомнил ли кто-то проверить, не работает.' },
      { node: 'gw', title: 'Срок считается в рабочих днях', body: 'Три рабочих дня от пятницы истекают в среду. Календарные сроки применяются только там, где ТЗ задаёт их явно — например, месяц пилота.' },
      { node: 'cause', title: 'Разбирается причина, а не факт', body: 'Просрочка может означать перегрузку ответственного, нехватку экспертизы или заниженный норматив. Реакция на каждую причину разная.' },
      { node: 'norm', title: 'Норматив можно изменить', body: 'Если срок систематически нарушается всеми, проблема в нормативе. Он правится в настройках процесса без участия разработчиков.' },
      { node: 'audit', title: 'Всё попадает в неизменяемый журнал', body: 'Записи связаны цепочкой хэшей: подмена или удаление задним числом ломает цепочку и выявляется проверкой целостности.' },
    ],
  },
  {
    id: 'dtszn-config', role: 'dtszn', group: 'ДТСЗН (центральный аппарат)',
    title: 'Настройка процесса без участия разработчиков',
    description: 'Адаптация конвейера к меняющимся условиям: этапы, сроки, критерии и ответственные роли задаются как данные.',
    lanes: [L.dtszn, L.sys],
    nodes: [
      { id: 'st', type: 'start', lane: 'dtszn', col: 0, row: 0, label: 'Аналитика показала узкое место процесса' },
      { id: 'find', type: 'user', lane: 'dtszn', col: 1, row: 0, label: 'Определить этап и характер проблемы' },
      { id: 'gw', type: 'xor', lane: 'dtszn', col: 2, row: 0, label: 'Что менять?' },
      { id: 'sla', type: 'user', lane: 'dtszn', col: 3, row: 0, label: 'Изменить срок и единицу измерения' },
      { id: 'crit', type: 'user', lane: 'dtszn', col: 3, row: 1, label: 'Скорректировать критерии Gate' },
      { id: 'role', type: 'user', lane: 'dtszn', col: 3, row: 2, label: 'Сменить ответственную роль' },
      { id: 'dec', type: 'user', lane: 'dtszn', col: 3, row: 3, label: 'Изменить перечень допустимых решений' },
      { id: 'save', type: 'service', lane: 'sys', col: 4, row: 0, label: 'Применить конфигурацию немедленно' },
      { id: 'audit', type: 'service', lane: 'sys', col: 5, row: 0, label: 'Записать изменение в журнал аудита' },
      { id: 'watch', type: 'user', lane: 'dtszn', col: 6, row: 0, label: 'Наблюдать за показателями этапа' },
      { id: 'end', type: 'end', lane: 'dtszn', col: 7, row: 0, label: 'Процесс адаптирован к реальным условиям' },
    ],
    flows: [
      { from: 'st', to: 'find' }, { from: 'find', to: 'gw' },
      { from: 'gw', to: 'sla', label: 'срок' }, { from: 'gw', to: 'crit', label: 'критерии' },
      { from: 'gw', to: 'role', label: 'ответственный' }, { from: 'gw', to: 'dec', label: 'решения' },
      { from: 'sla', to: 'save', kind: 'message' }, { from: 'crit', to: 'save', kind: 'message' },
      { from: 'role', to: 'save', kind: 'message' }, { from: 'dec', to: 'save', kind: 'message' },
      { from: 'save', to: 'audit' }, { from: 'audit', to: 'watch', kind: 'message' }, { from: 'watch', to: 'end' },
    ],
    walkthrough: [
      { node: 'st', title: 'Изменение начинается с данных', body: 'Не с ощущения, что «процесс неудобный», а с показателя: соблюдение SLA на конкретном этапе упало, или большинство инициатив останавливается на одной точке.' },
      { node: 'gw', title: 'Четыре рычага настройки', body: 'Срок, критерии, ответственная роль и перечень допустимых решений. Этого достаточно, чтобы перестроить процесс без изменения кода.' },
      { node: 'save', title: 'Изменения вступают в силу сразу', body: 'Новая конфигурация применяется к инициативам, которые придут на этот этап далее. Уже принятые решения не пересчитываются.' },
      { node: 'watch', title: 'Настройка — это цикл, а не разовое действие', body: 'После изменения смотрите на тот же показатель через несколько недель. Экосистема должна постоянно самооцениваться и адаптироваться.' },
    ],
  },
];

export function diagramsForRole(role) {
  if (!role || role === 'all') return DIAGRAMS;
  return DIAGRAMS.filter((d) => d.role === role || d.role === 'all');
}

export const ROLE_ORDER = ['all', 'employee', 'head', 'expert', 'developer', 'supplier', 'pilot_coordinator', 'dtszn'];
